Story/69064 --> Release
prefeiturasp/SME-NovoSGP pull request #10093
Opened 2022-07-21 18:22 UTC by viniciusnyari

AB#69064
AB#69780

2022-07-21 21:38 UTC, rafalosiamcom requested changes

2022-07-21 21:38 UTC, rafalosiamcom commented on src/SME.SGP.IoC/Extensions/RegistrarTelemetria.cs
> +            // if (configuration == null)
não da pra subir esse codigo assim.. pois não vai mais configurar Telemetria na subida da API e Workers

2022-07-21 21:38 UTC, rafalosiamcom commented on src/SME.SGP.IoC/RegistrarDependencias.cs
> +            // if (configuration == null)
não pode subir esse codigo dando return sempre

2022-07-22 11:21 UTC, FernandoGroeler commented on src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfilPlanejamento/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfilPlanejamentoQuery.cs
> +}
Falto adicionar o Validator.

2022-07-22 11:21 UTC, FernandoGroeler commented on src/SME.SGP.Aplicacao/Queries/Disciplina/ObterComponentesRegenciaPorAno/ObterComponentesRegenciaPorAnoQuery.cs
> +}
Falto adicionar o validator.

2022-07-22 11:21 UTC, FernandoGroeler commented on src/SME.SGP.IoC/Extensions/RegistrarTelemetria.cs
> +            // if (configuration == null)
Retirar esse comentário do código.

2022-07-22 11:21 UTC, FernandoGroeler commented on src/SME.SGP.IoC/RegistrarDependencias.cs
> +            // if (configuration == null)
Manter o código retirando o comentário.

2022-07-22 11:30 UTC, viniciusnyari commented on src/SME.SGP.IoC/RegistrarDependencias.cs
> +            // if (configuration == null)
Resolvido

2022-07-22 11:33 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfilPlanejamento/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfilPlanejamentoQuery.cs
> +}
Adicionado.

2022-07-22 11:33 UTC, viniciusnyari commented on src/SME.SGP.IoC/Extensions/RegistrarTelemetria.cs
> +            // if (configuration == null)
Removido

2022-07-22 11:34 UTC, viniciusnyari commented on src/SME.SGP.IoC/Extensions/RegistrarTelemetria.cs
> +            // if (configuration == null)
Resolvido

2022-07-22 11:34 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Queries/Disciplina/ObterComponentesRegenciaPorAno/ObterComponentesRegenciaPorAnoQuery.cs
> +}
Adicionado

2022-07-22 11:34 UTC, viniciusnyari commented on src/SME.SGP.IoC/RegistrarDependencias.cs
> +            // if (configuration == null)
Removido

2022-07-22 13:11 UTC, FernandoGroeler approved these changes

2022-07-22 18:16 UTC, rafalosiamcom requested changes

2022-07-22 19:37 UTC, viniciusnyari commented on teste/SME.SGP.TesteIntegracao/NotaFechamentoFinal/Ao_excluir_nota_conceito.cs
> +                ObterPerfilDiretor(),
Ajustado.

2022-07-22 19:44 UTC, viniciusnyari commented on src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
> +            if (!usuario.EhProfessorCj() && !podePersistir)
Ajustado

2022-07-22 19:48 UTC, viniciusnyari commented on teste/SME.SGP.TesteIntegracao/NotaFechamentoFinal/Ao_lancar_nota_bimestre_encerrado.cs
> +        public async Task Deve_permitir_lancamento_nota_para_professor_com_atribuicao()
Mas esse cenário não está olhando para período de abertura e reabertura e sim se ele tem atribuição.

2022-07-23 02:01 UTC, viniciusnyari commented on teste/SME.SGP.TesteIntegracao/NotaFechamentoFinal/Ao_lancar_nota_bimestre_encerrado.cs
> +        public async Task Deve_permitir_lancamento_nota_para_professor_com_atribuicao()
É que esse teste foi aproveitado para fazer o de atribuição encerrada (antes do encerramento pode e depois não pode)
"Lançamento de nota por professor com atribuição encerrada (antes do encerramento pode e depois não pode)."

2022-07-26 01:28 UTC, rafalosiamcom approved these changes

2022-07-26 01:28 UTC, merged