Tela de Frequência do Listão - Persistência dos dados (Apenas em HOM)
prefeiturasp/SME-NovoSGP pull request #10095
Opened 2022-07-22 19:35 UTC by thiiagofernando

AB#70315
AB#70377 

Ajustes na consulta SQL de ObterRegistroAusenciaPorIdRegistro para retornar todos os dados da entidade registro frequencia aluno com o Id da Aula

2022-07-25 11:17 UTC, viniciusnyari approved these changes

2022-07-25 12:17 UTC, rafalosiamcom requested changes

2022-07-25 12:17 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs
> +							INNER JOIN aula a ON rf.aula_id = a.id
registro_frequencia_aluno agora tem a coluna aula_id
![image](https://user-images.githubusercontent.com/57261028/180775659-92c5a36c-7c6f-4c0b-8578-c7253b52366e.png)
não precisa fazer os joins até aula

2022-07-25 17:06 UTC, thiiagofernando commented on src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs
> +							INNER JOIN aula a ON rf.aula_id = a.id
removido join

2022-07-26 16:49 UTC, rafalosiamcom approved these changes

2022-07-26 16:49 UTC, merged