[Modernização] Testes automatizados - Compensação de ausência (Integração)
prefeiturasp/SME-NovoSGP pull request #10109
Opened 2022-07-27 20:33 UTC by FernandoGroeler

AB#69046
AB#69162
AB#69165
AB#69166
AB#69167
AB#69168
AB#69169
AB#69160
AB#69161
AB#69154
AB#70501

2022-07-27 22:21 UTC, viniciusnyari requested changes

2022-07-27 22:21 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Queries/EOL/Professor/ProfessorPodePersistirTurma/ProfessorPodePersistirTurmaQuery.cs
> +                .WithMessage("Informe o rf do profesor para verificação.");
Aqui precisamos detalhar mais. Exemplo: "Informe o rf do profesor para verificação se o professor pode persistir na turma".

2022-07-27 22:21 UTC, viniciusnyari commented on src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs
> +                    await consultasTurma.TurmaEmPeriodoAberto(turma, DateTime.Today, bimestre, false, tipoCalendario);
Acho que essa aqui poderia usar aquela query mediator padrão que usamos em todo o sistema.

2022-07-28 02:14 UTC, viniciusnyari requested changes

2022-07-28 02:14 UTC, viniciusnyari commented on teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs
> +            return await Task.FromResult(true);
Esse método poderia ser removido, para aos poucos irmos inutilizando o servicoEol, bem como o fake dele, já que estamos usando query mediator.

2022-07-28 11:37 UTC, viniciusnyari approved these changes

2022-07-28 18:12 UTC, rafalosiamcom approved these changes

2022-07-28 18:12 UTC, merged