corerção tela de notas
prefeiturasp/SME-NovoSGP pull request #10247
Opened 2022-08-16 20:53 UTC by danilosoad

AB#72062

2022-08-16 20:54 UTC, viniciusnyari approved these changes

2022-08-17 12:22 UTC, rafalosiamcom requested changes

2022-08-17 12:22 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolarConsulta.cs
> +                var periodoReferencia = bimestre == 1 ? "periodo_inicio < @dataReferencia" : "periodo_fim > @dataReferencia";
essa regra se aplica a semestre e não bimestre

2022-08-24 11:12 UTC, rafalosiamcom approved these changes

2022-08-24 11:12 UTC, merged