Fechamento de bimestre - Não está gravando a nota do estudante (Ano Anterior)
prefeiturasp/SME-NovoSGP pull request #10248
Opened 2022-08-16 21:12 UTC by FernandoGroeler

AB#72100

2022-08-17 13:03 UTC, rafalosiamcom requested changes

2022-08-17 13:03 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoFinal.cs
> +                fechamentoFinalSalvarDto.DisciplinaId, fechamentoFinalSalvarDto.TurmaCodigo));
Atualizar o cache ao invés de remover

2022-08-17 17:06 UTC, FernandoGroeler commented on src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoFinal.cs
> +                fechamentoFinalSalvarDto.DisciplinaId, fechamentoFinalSalvarDto.TurmaCodigo));
Implementado para inserir e/ou atualizar no cache ao invés de remover.

2022-08-22 11:40 UTC, rafalosiamcom approved these changes

2022-08-22 11:40 UTC, merged