Na tela dos bimestres está exibindo a flag de aguardando aprovação da…
prefeiturasp/SME-NovoSGP pull request #10245
Opened 2022-08-16 20:08 UTC by DanylloAntunes

AB#72101

2022-08-16 20:36 UTC, viniciusnyari approved these changes

2022-08-17 18:58 UTC, rafalosiamcom requested changes

2022-08-17 18:58 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
> +                && !(await servicoUsuario.ObterUsuarioLogado()).EhGestorEscolar()
alterar para a query mediator ObterUsuarioLogado

2022-08-17 19:08 UTC, DanylloAntunes commented on src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
> +                && !(await servicoUsuario.ObterUsuarioLogado()).EhGestorEscolar()
Alteração feita!

2022-08-19 12:05 UTC, rafalosiamcom approved these changes

2022-08-19 12:05 UTC, merged