Correção requisição imagem miniIO
prefeiturasp/SME-NovoSGP pull request #10304
Opened 2022-08-24 20:01 UTC by danilosoad

AB#72771

2022-08-25 11:58 UTC, viniciusnyari approved these changes

2022-08-29 13:08 UTC, rafalosiamcom requested changes

2022-08-29 13:08 UTC, rafalosiamcom commented on src/SME.SGP.Infra/Servicos/ServicoArmazenamento/ServicoArmazenamento.cs
> +            return await Task.FromResult($"{hostAplicacao}{bucketName}/{nomeArquivo}");
```suggestion
            return $"{hostAplicacao}{bucketName}/{nomeArquivo}";
```

2022-08-29 17:32 UTC, rafalosiamcom approved these changes

2022-08-29 17:32 UTC, merged