BUG 72123 - Correção lançar nota pós conselho aluno inativo no ano anterior
prefeiturasp/SME-NovoSGP pull request #10357
Opened 2022-08-30 18:53 UTC by danilosoad

AB#72123

2022-08-31 13:19 UTC, viniciusnyari requested changes

2022-08-31 13:19 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
> +                if (periodoInicio.Year >= DateTime.Now.Year)
E quando for ano anterior?

2022-08-31 13:19 UTC, viniciusnyari commented on src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
> +                CodigoSituacaoMatricula != SituacaoMatriculaAluno.Concluido &&
Estou na dúvida dessa situação

2022-09-01 13:05 UTC, rafalosiamcom approved these changes

2022-09-01 13:05 UTC, merged