71987 - Ajustes na nota pós-conselho vazia (Numérica e Conceito)
prefeiturasp/SME-NovoSGP pull request #10429
Opened 2022-09-09 18:38 UTC by FernandoGroeler

AB#71987

2022-09-09 18:41 UTC, viniciusnyari requested changes

2022-09-09 18:41 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/SalvarConselhoClasseAlunoNotaUseCase.cs
> +                        "O conceito pós-conselho deve ser informado no conselho de classe do aluno.");
Coloca naquelas constantes

2022-09-09 18:46 UTC, viniciusnyari approved these changes

2022-09-13 19:46 UTC, rafalosiamcom requested changes

2022-09-13 20:44 UTC, rafalosiamcom approved these changes

2022-09-13 20:44 UTC, merged