Conselho de Classe - Nota pós-conselho bimestre não exibida na aba Final
prefeiturasp/SME-NovoSGP pull request #10624
Opened 2022-09-27 17:18 UTC by thiiagofernando

Conselho de Classe - Nota pós-conselho bimestre não exibida na aba Final
AB#75086
AB#75189

2022-09-27 18:14 UTC, viniciusnyari approved these changes

2022-09-28 13:03 UTC, rafalosiamcom requested changes

2022-09-28 13:03 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasFinaisBimestresAluno/ObterNotasFinaisBimestresAlunoQueryHandler.cs
> +            return await repositorioConselhoClasseNota.ObterNotasFinaisBimestresAlunoAsync(request.AlunoCodigo,request.TurmasCodigos,request.Bimestre,request.DataMatricula,request.DataSituacao,reques
Retornar as Queries distintas para notas de Fechamento e Conselho para uso do cache

2022-09-28 13:44 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasFinaisBimestresAluno/ObterNotasFinaisBimestresAlunoQueryHandler.cs
> +            return await repositorioConselhoClasseNota.ObterNotasFinaisBimestresAlunoAsync(request.AlunoCodigo,request.TurmasCodigos,request.Bimestre,request.DataMatricula,request.DataSituacao,reques
ajustado

2022-09-28 13:54 UTC, rafalosiamcom approved these changes

2022-09-28 13:54 UTC, merged