[70490 Melhorias no Listão]  Notas do bimestre não refletem na aba final
prefeiturasp/SME-NovoSGP pull request #10649
Opened 2022-09-29 12:13 UTC by FernandoGroeler

AB#74426

2022-09-29 12:15 UTC, viniciusnyari approved these changes

2022-09-29 12:37 UTC, rafalosiamcom requested changes

2022-09-29 12:37 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
> +        private async Task InserirOuAtualizarCache(FechamentoFinalTurmaDisciplinaDto fechamentoFinalTurmaDisciplina, bool emAprovacao)
Esse método foi copiado de ComandosFechamentoFinal, ao invés de duplicar o código transforme ele em um command mediator para aproveitamento do método.

2022-09-30 12:35 UTC, rafalosiamcom approved these changes

2022-09-30 12:35 UTC, merged