Story/77316 - API SGP
prefeiturasp/SME-NovoSGP pull request #11015
Opened 2022-11-08 19:08 UTC by thiiagofernando

AB#77316

2022-11-08 19:46 UTC, rafalosiamcom requested changes

2022-11-08 19:46 UTC, rafalosiamcom commented on src/SME.SGP.Api/Controllers/FuncionarioController.cs
> +            this.mediator = mediator;
injetando Mediator no controller ?
tem que ser criado e injetado o UseCase no controller conforme orientação do padrão Mediator na Wiki
https://dev.azure.com/amcomgov/Novo%20SGP/_wiki/wikis/Novo-SGP.wiki/359/Mediator

2022-11-08 19:46 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/Ocorrencia/AlterarOcorrencia/AlterarOcorrenciaCommandHandler.cs
> +        private readonly IRepositorioOcorrenciaServidor _repositorioOcorrenciaServidor;
não utilizamos o prefixo _ nas variaveis privadas

2022-11-08 19:46 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Queries/Ocorrencia/OcorrenciaServidor/ObterOcorrenciasServidorPorIdOcorrencia/ObterOcorrenciasServidorPorIdOcorrenciaQueryHandler.cs
> +        private readonly IRepositorioOcorrenciaServidor _repositorioOcorrenciaServidor;
remover prefixo _

2022-11-08 19:48 UTC, viniciusnyari commented on src/SME.SGP.Api/Controllers/RegistroIndividualController.cs
> +        [Permissao(Permissao.OCO_C, Policy = "Bearer")]
Duas permissões?

2022-11-08 19:48 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Commands/Ocorrencia/AlterarOcorrencia/AlterarOcorrenciaCommand.cs
> -                .WithMessage("Os alunos envolvidos na ocorrência devem ser informados.");
Complementa a mensagem "...para alteração de ocorrência"

2022-11-08 19:50 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Commands/Ocorrencia/InserirOcorrencia/InserirOcorrenciaCommand.cs
> +                .WithMessage("A Ue da ocorrência deve ser informada.");
Complementa a mensagem, igual ao lá de cima

2022-11-08 19:51 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Commands/Ocorrencia/InserirOcorrencia/InserirOcorrenciaCommandHandler.cs
> +                        throw new NegocioException(MensagemNegocioComuns.Data_da_ocorrencia_nao_pode_ser_futura);
Essa mensagem não é comum, é específica de ocorrência e poderia ser uma nova constante, mas...

2022-11-08 19:51 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Commands/OcorrenciaServidor/ExcluirOcorrenciaServidor/ExcluirOcorrenciaServidorPorIdOcorrencia/ExcluirOcorrenciaServidorPorIdOcorrenciaCommandHandler.cs
> +           return Unit.Value;
não entendi esse retorno

2022-11-08 19:52 UTC, Jailsvs approved these changes

2022-11-08 19:53 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Queries/Ocorrencia/OcorrenciaServidor/ObterOcorrenciasServidorPorIdOcorrencia/ObterOcorrenciasServidorPorIdOcorrenciaQuery.cs
> +            IdOcorrencia = idOcorrencia;
Sem validação?

2022-11-08 19:54 UTC, viniciusnyari commented on src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs
> +        public const string Data_da_ocorrencia_nao_pode_ser_futura = "A data da ocorrência não pode ser futura.";
Essa mensagem não é comum, é específica da funcionalidade. Essa do Plano_aee tbém :)

2022-11-08 19:56 UTC, viniciusnyari commented on teste/SME.SGP.TesteIntegracao/Ocorrencia/Ao_filtrar_ocorrencia.cs
> +                AnoLetivo = 2022,
Substitui esse ano letivo fixo por year do datetime extensions (ver todos)

2022-11-08 20:49 UTC, thiiagofernando commented on src/SME.SGP.Api/Controllers/FuncionarioController.cs
> +            this.mediator = mediator;
criado usecase para remover o mediator da controller

2022-11-08 20:50 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/Commands/Ocorrencia/AlterarOcorrencia/AlterarOcorrenciaCommandHandler.cs
> +        private readonly IRepositorioOcorrenciaServidor _repositorioOcorrenciaServidor;
removido prefixo

2022-11-08 20:51 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/Queries/Ocorrencia/OcorrenciaServidor/ObterOcorrenciasServidorPorIdOcorrencia/ObterOcorrenciasServidorPorIdOcorrenciaQueryHandler.cs
> +        private readonly IRepositorioOcorrenciaServidor _repositorioOcorrenciaServidor;
removido prefixo

2022-11-08 20:53 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/Commands/Ocorrencia/AlterarOcorrencia/AlterarOcorrenciaCommand.cs
> -                .WithMessage("Os alunos envolvidos na ocorrência devem ser informados.");
essa parte do código esta sendo removido

2022-11-08 20:56 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/Commands/Ocorrencia/InserirOcorrencia/InserirOcorrenciaCommand.cs
> +                .WithMessage("A Ue da ocorrência deve ser informada.");
ajustado a frase

2022-11-08 21:02 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/Commands/Ocorrencia/InserirOcorrencia/InserirOcorrenciaCommandHandler.cs
> +                        throw new NegocioException(MensagemNegocioComuns.Data_da_ocorrencia_nao_pode_ser_futura);
criando uma constante especifica

2022-11-08 21:05 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/Queries/Ocorrencia/OcorrenciaServidor/ObterOcorrenciasServidorPorIdOcorrencia/ObterOcorrenciasServidorPorIdOcorrenciaQuery.cs
> +            IdOcorrencia = idOcorrencia;
Criado validação

2022-11-08 21:06 UTC, thiiagofernando commented on src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs
> +        public const string Data_da_ocorrencia_nao_pode_ser_futura = "A data da ocorrência não pode ser futura.";
Criando uma constante para ocorrencia

2022-11-08 21:07 UTC, thiiagofernando commented on teste/SME.SGP.TesteIntegracao/Ocorrencia/Ao_filtrar_ocorrencia.cs
> +                AnoLetivo = 2022,
removido ano fixo

2022-11-08 21:15 UTC, thiiagofernando commented on src/SME.SGP.Api/Controllers/FuncionarioController.cs
> +        [Permissao(Permissao.OCO_C, Policy = "Bearer")]
Sim , esse endpoint tem duas permissões

2022-11-08 21:15 UTC, thiiagofernando commented on src/SME.SGP.Api/Controllers/RegistroIndividualController.cs
> +        [Permissao(Permissao.OCO_C, Policy = "Bearer")]
Sim , esse endpoint tem duas permissões

2022-11-08 21:18 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/Commands/OcorrenciaServidor/ExcluirOcorrenciaServidor/ExcluirOcorrenciaServidorPorIdOcorrencia/ExcluirOcorrenciaServidorPorIdOcorrenciaCommandHandler.cs
> +           return Unit.Value;
ajustado retorno

2022-11-09 14:53 UTC, rafalosiamcom approved these changes

2022-11-09 14:53 UTC, merged