79511 - Criar endpoint de retorno de situação e prioridade do naapa
prefeiturasp/SME-NovoSGP pull request #11122
Opened 2022-11-18 21:02 UTC by DanylloAntunes

AB#79511

2022-11-18 21:24 UTC, viniciusnyari requested changes

2022-11-18 21:24 UTC, viniciusnyari commented on src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs
> +        [Permissao(Permissao.AEE_C, Policy = "Bearer")]
Tem que usar a permissão do NAAPA

2022-11-18 21:24 UTC, viniciusnyari commented on src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs
> +        [Permissao(Permissao.AEE_C, Policy = "Bearer")]
Tem que usar a permissão do NAAPA

2022-11-18 21:24 UTC, viniciusnyari commented on src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs
> +        [ProducesResponseType(typeof(IEnumerable<EnumeradoRetornoDto>), 200)]
Substitua o nome desse por SituacaoEncaminhamentoNAAPADto

2022-11-18 21:24 UTC, viniciusnyari commented on src/SME.SGP.Dados/Repositorios/RepositorioQuestaoEncaminhamentoNAAPA.cs
> +                            where sen.etapa = 1 and qta.nome = 'Prioridade'
Coloque esses como constantes

2022-11-21 11:08 UTC, DanylloAntunes commented on src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs
> +        [Permissao(Permissao.AEE_C, Policy = "Bearer")]
feito

2022-11-21 11:09 UTC, DanylloAntunes commented on src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs
> +        [ProducesResponseType(typeof(IEnumerable<EnumeradoRetornoDto>), 200)]
Não a necessidade pois o dto generico de enum atende.

2022-11-21 11:14 UTC, DanylloAntunes commented on src/SME.SGP.Dados/Repositorios/RepositorioQuestaoEncaminhamentoNAAPA.cs
> +                            where sen.etapa = 1 and qta.nome = 'Prioridade'
feito

2022-11-21 11:37 UTC, merged