Story/64234 --> DEV
prefeiturasp/SME-NovoSGP pull request #11160
Opened 2022-11-23 02:04 UTC by viniciusnyari

2022-11-23 11:22 UTC, rafalosiamcom requested changes

2022-11-23 11:22 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs
> +                           and ea.situacao not in (4, 5, 8, 10)
Não temos essas situações no encaminhamento NAAPA.
A unica situação existente é a 1

2022-11-23 11:22 UTC, rafalosiamcom commented on teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_cadastrar_editar_encaminhamento_naapa_rascunho.cs
> +        [Fact(DisplayName = "Encaminhamento NAAPA - Cadastrar encaminhamento NAAPA")]
pode testar se só gerou um registro no banco também por exemplo, pra garantir que não esteja duplicando registros

2022-11-23 11:22 UTC, rafalosiamcom commented on teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_cadastrar_editar_encaminhamento_naapa_rascunho.cs
> +        [Fact(DisplayName = "Encaminhamento NAAPA - Alterar encaminhamento NAAPA")]
teste se não duplicou registro ao alterar

2022-11-23 11:50 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoNAAPAUseCase.cs
> +namespace SME.SGP.Aplicacao.CasosDeUso
Ok

2022-11-23 12:09 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoNAAPAUseCase.cs
> +        private readonly IRepositorioQuestaoEncaminhamentoNAAPA repositorioQuestaoEncaminhamentoNAAPA;
Resolvido

2022-11-23 12:19 UTC, viniciusnyari commented on teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_cadastrar_editar_encaminhamento_naapa_rascunho.cs
> +        [Fact(DisplayName = "Encaminhamento NAAPA - Cadastrar encaminhamento NAAPA")]
Ajustado

2022-11-23 12:22 UTC, viniciusnyari commented on teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_cadastrar_editar_encaminhamento_naapa_rascunho.cs
> +        [Fact(DisplayName = "Encaminhamento NAAPA - Alterar encaminhamento NAAPA")]
Ajustado

2022-11-23 12:34 UTC, viniciusnyari commented on src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs
> +                           and ea.situacao not in (4, 5, 8, 10)
Ajustado

2022-11-23 12:34 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoNAAPAUseCase.cs
> +            var turma = await mediator.Send(new ObterTurmaComUeEDrePorIdQuery(encaminhamentoNAAPADto.TurmaId));
Ajustado

2022-11-23 12:45 UTC, viniciusnyari commented on src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs
> +                           and ea.situacao not in (4, 5, 8, 10)
Removido

2022-11-24 02:19 UTC, rafalosiamcom approved these changes

2022-11-24 02:19 UTC, merged