Story/64612 - Registro de itinerância  Anexos - API SGP
prefeiturasp/SME-NovoSGP pull request #11162
Opened 2022-11-23 10:43 UTC by thiiagofernando

AB#64612

2022-11-23 12:02 UTC, Jailsvs approved these changes

2022-11-24 01:13 UTC, rafalosiamcom requested changes

2022-11-24 01:13 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ExcluirArquivoItineranciaUseCase.cs
> +    public class ExcluirArquivoItineranciaUseCase :AbstractUseCase, IExcluirArquivoItineranciaUseCase
Não tem teste nessa classe

2022-11-24 01:13 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/Itinerancia/UploadArquivo/UploadArquivoItineranciaCommandHandler.cs
> +        public async Task<ArquivoArmazenadoItineranciaDto> Handle(UploadArquivoItineranciaCommand request, CancellationToken cancellationToken)
Faltou criar os testes automatizados do upload

2022-11-24 18:30 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ExcluirArquivoItineranciaUseCase.cs
> +    public class ExcluirArquivoItineranciaUseCase :AbstractUseCase, IExcluirArquivoItineranciaUseCase
Teste Criado

2022-11-24 18:30 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/Commands/Itinerancia/UploadArquivo/UploadArquivoItineranciaCommandHandler.cs
> +        public async Task<ArquivoArmazenadoItineranciaDto> Handle(UploadArquivoItineranciaCommand request, CancellationToken cancellationToken)
Teste Criado

2022-11-25 15:24 UTC, rafalosiamcom approved these changes

2022-11-25 15:24 UTC, merged