Story/82215
prefeiturasp/SME-NovoSGP pull request #11618
Opened 2023-01-11 11:31 UTC by Jailsvs

AB#82215
AB#83123

2023-01-11 11:53 UTC, FernandoGroeler approved these changes

2023-01-11 12:45 UTC, rafalosiamcom requested changes

2023-01-11 12:45 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioRespostaEncaminhamentoNAAPA.cs
> +            var query = @"select enr.*, enq.*, q.* from encaminhamento_naapa_resposta enr
Esta carregando muita informação do banco, só precisa da QuestaoId e do objeto Resposta

2023-01-11 12:45 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/AtualizarEnderecoDoEncaminhamentoNAAPAUseCase.cs
> +            if (respostasEnderecoResidencialNAAPA == null) return false;
Se não tiver registro de resposta no banco atualmente mas retornou um endereço do EOL, esta abortando o processo e não vai fazer a atualização.

Esse tipo de teste tem que ser automatizado

2023-01-11 12:45 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/AtualizarTurmaDoEncaminhamentoNAAPAUseCase.cs
> +            if (alunoTurma != null && alunoTurma.AnoLetivo == DateTime.Now.Year && alunoTurma.DataSituacao.Date <= DateTime.Now.Date)
Essa regra esta errada, não deve ser filtrado e sim priorizado por data e ano.

2023-01-11 12:45 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosComSituacaoDiferenteDeEncerrado/ObterEncaminhamentosComSituacaoDiferenteDeEncerradoQueryHandler.cs
> +            return await this.repositorioEncaminhamentoNaapa.ObterEncaminhamentosComSituacaoDiferenteDeEncerrado();
```suggestion
        public Task<IEnumerable<EncaminhamentoNAAPADto>> Handle(ObterEncaminhamentosComSituacaoDiferenteDeEncerradoQuery request, CancellationToken cancellationToken)
        {
            return this.repositorioEncaminhamentoNaapa.ObterEncaminhamentosComSituacaoDiferenteDeEncerrado();
```

2023-01-11 13:17 UTC, Jailsvs commented on src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/AtualizarEnderecoDoEncaminhamentoNAAPAUseCase.cs
> +            if (respostasEnderecoResidencialNAAPA == null) return false;
Sempre terá resposta no banco, pois quando não existe endereço no EOL a resposta é gravada em branco.

2023-01-11 16:59 UTC, Jailsvs commented on src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/AtualizarEnderecoDoEncaminhamentoNAAPAUseCase.cs
> +            if (respostasEnderecoResidencialNAAPA == null) return false;
Ajuste será efetuado para caso não exista registro de resposta persistido

2023-01-11 16:59 UTC, Jailsvs commented on src/SME.SGP.Dados/Repositorios/RepositorioRespostaEncaminhamentoNAAPA.cs
> +            var query = @"select enr.*, enq.*, q.* from encaminhamento_naapa_resposta enr
Ajuste efetuado para reduzir carga do retorno

2023-01-11 18:38 UTC, Jailsvs commented on src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/AtualizarTurmaDoEncaminhamentoNAAPAUseCase.cs
> +            if (alunoTurma != null && alunoTurma.AnoLetivo == DateTime.Now.Year && alunoTurma.DataSituacao.Date <= DateTime.Now.Date)
Ajustado regra porém avaliaremos em conjunto com Losi

2023-01-12 12:35 UTC, rafalosiamcom approved these changes

2023-01-12 12:35 UTC, merged