Story/83995
prefeiturasp/SME-NovoSGP pull request #11679
Opened 2023-01-19 18:26 UTC by DanylloAntunes

AB#83995

2023-01-19 18:35 UTC, viniciusnyari approved these changes

2023-01-19 18:58 UTC, rafalosiamcom requested changes

2023-01-19 18:58 UTC, rafalosiamcom commented on src/SME.SGP.Dominio/Enumerados/TipoEscola.cs
> +        EMEIPFOM = 31
Tipo 31 já existe na lista

2023-01-19 18:59 UTC, rafalosiamcom commented
Faltou vincular a história de Liberação também

2023-01-20 11:42 UTC, rafalosiamcom approved these changes

2023-01-20 11:42 UTC, merged