Story/84121 --> R2
prefeiturasp/SME-NovoSGP pull request #11677
Opened 2023-01-19 16:48 UTC by viniciusnyari

[AB#84121](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84121)
[AB#84251](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84251)

2023-01-19 18:01 UTC, rafalosiamcom requested changes

2023-01-19 18:01 UTC, rafalosiamcom commented on teste/SME.SGP.TesteIntegracao/Aula/Base/AulaTeste.cs
> +        protected async Task CriarDadosBasicosAula(string perfil, Modalidade modalidade, ModalidadeTipoCalendario tipoCalendario)
Criou outro método com mesmo nome e assinatura ?
quando usar um ou outro ?
esses nomes estão confusos

2023-01-19 18:04 UTC, rafalosiamcom requested changes

2023-01-19 18:04 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Aula/ObterAulasPorTurmaComponenteDataUseCase.cs
> +            => aulaId == 0;
Isso não é usado

2023-01-19 18:04 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Aula/ObterAulasPorTurmaComponenteDataUseCase.cs
> +        private async Task<bool> AlterandoDataAula(long aulaId, DateTime dataAula)
Método não utilizado

2023-01-19 18:05 UTC, viniciusnyari commented on teste/SME.SGP.TesteIntegracao/Aula/Base/AulaTeste.cs
> +        protected async Task CriarDadosBasicosAula(string perfil, Modalidade modalidade, ModalidadeTipoCalendario tipoCalendario)
Ajustado

2023-01-19 18:08 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/Aula/ObterAulasPorTurmaComponenteDataUseCase.cs
> +        private async Task<bool> AlterandoDataAula(long aulaId, DateTime dataAula)
Removido

2023-01-19 18:08 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/Aula/ObterAulasPorTurmaComponenteDataUseCase.cs
> +            => aulaId == 0;
Removido

2023-01-20 11:40 UTC, rafalosiamcom approved these changes

2023-01-20 11:40 UTC, merged