SGP - story/85760 --> MASTER
prefeiturasp/SME-NovoSGP pull request #11802
Opened 2023-02-13 11:48 UTC by viniciusnyari

AB#85760
AB#85543

2023-02-16 15:54 UTC, rafalosiamcom requested changes

2023-02-16 15:54 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs
> +                                left join usuario u on coalesce(u.rf_codigo,login) = sed.supervisor_id
rf_codigo e login tem o mesmo valor, então é um custo adicionar desnecessário incluir esse coalesce na query

2023-02-17 01:33 UTC, viniciusnyari commented on src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs
> +                                left join usuario u on coalesce(u.rf_codigo,login) = sed.supervisor_id
Ajustado

2023-02-17 14:19 UTC, rafalosiamcom approved these changes

2023-02-17 14:19 UTC, merged