API SGP - Story/60323
prefeiturasp/SME-NovoSGP pull request #11868
Opened 2023-02-22 11:33 UTC by thiiagofernando

AB#60323

2023-02-22 12:34 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/CasosDeUso/ParametrosAnoAnterior/ReplicarParametrosAnoAnteriorUseCase.cs
> +                throw new NegocioException($"Não foi possivel resplicar para o ano {filtro.AnoLetivo} e a modalidade {filtro.ModalidadeTipoCalendario.Name()}");
Ajustado

2023-02-22 12:54 UTC, viniciusnyari approved these changes

2023-02-22 13:36 UTC, rafalosiamcom requested changes

2023-02-22 13:36 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioPendenciaCalendarioUe.cs
> +                              AND tc.ano_letivo = @anoLetivo
pode filtrar o ano da turma, assim não precisa do join com tipo_calendario

2023-02-22 13:36 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/PendenciaCalendarioUe/RemoverPendenciasCalendarioNoFinalDoAnoLetivoUseCase.cs
> +                    LogContexto.Calendario,
o Contexto é pendencia, pois a rotina trata de remoção de pendências

2023-02-22 13:36 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/PendenciaCalendarioUe/ExcluirPendenciaCalendarioAnoAnteriorCalendarioUseCase.cs
> +                    LogContexto.Calendario,
o Contexto é pendencia, pois a rotina trata de remoção de pendências

2023-02-22 13:36 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/PendenciaCalendarioUe/ExcluirPendenciaCalendarioAnoAnteriorCalendarioPoUeUseCase.cs
> +                    LogContexto.Calendario,
o Contexto é pendencia, pois a rotina trata de remoção de pendências

2023-02-22 13:50 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/CasosDeUso/PendenciaCalendarioUe/ExcluirPendenciaCalendarioAnoAnteriorCalendarioPoUeUseCase.cs
> +                    LogContexto.Calendario,
Alterado o Contexto

2023-02-22 13:50 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/CasosDeUso/PendenciaCalendarioUe/ExcluirPendenciaCalendarioAnoAnteriorCalendarioUseCase.cs
> +                    LogContexto.Calendario,
Alterado o Contexto

2023-02-22 13:50 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/CasosDeUso/PendenciaCalendarioUe/RemoverPendenciasCalendarioNoFinalDoAnoLetivoUseCase.cs
> +                    LogContexto.Calendario,
Alterado o Contexto

2023-02-22 14:06 UTC, thiiagofernando commented on src/SME.SGP.Dados/Repositorios/RepositorioPendenciaCalendarioUe.cs
> +                              AND tc.ano_letivo = @anoLetivo
removido join com tipo_calendario

2023-02-22 20:47 UTC, thiiagofernando commented
Criado os testes de integração

2023-02-23 12:35 UTC, rafalosiamcom approved these changes

2023-02-23 12:35 UTC, merged