Story/60676
prefeiturasp/SME-NovoSGP pull request #11989
Opened 2023-03-07 13:08 UTC by DanylloAntunes

AB#60676
AB#87954

2023-03-07 18:43 UTC, Jailsvs approved these changes

2023-03-07 20:11 UTC, rafalosiamcom requested changes

2023-03-07 20:11 UTC, rafalosiamcom commented on src/SME.SGP.Api/Controllers/HistoricoEscolarController.cs
> +        [Route("observacao-complementar/{codigoAluno}")]
ajustar padrão da rota para aluno/{codigoAluno}/observacao-complementar

2023-03-07 20:11 UTC, rafalosiamcom commented on src/SME.SGP.Api/Controllers/HistoricoEscolarController.cs
> +        [Route("observacao-complementar")]
ajustar padrão da rota para aluno/{codigoAluno}/observacao-complementar

2023-03-08 14:51 UTC, rafalosiamcom approved these changes

2023-03-08 14:51 UTC, merged