Label de "Aguardando Aprovação" no Listão aplicado para todos os alunos
prefeiturasp/SME-NovoSGP pull request #12043
Opened 2023-03-13 16:47 UTC by thiiagofernando

AB#88617

2023-03-13 16:50 UTC, viniciusnyari requested changes

2023-03-13 16:50 UTC, viniciusnyari commented on src/SME.SGP.Dados/Repositorios/RepositorioNotasConceitosConsulta.cs
> +            var sql = $@"select coalesce(coalesce(coalesce(w.nota, fn.nota), coalesce(w.nota, w.conceito_id), -1))
Tem certeza que esse negócio vai funcionar?

2023-03-13 16:52 UTC, thiiagofernando commented on src/SME.SGP.Dados/Repositorios/RepositorioNotasConceitosConsulta.cs
> +            var sql = $@"select coalesce(coalesce(coalesce(w.nota, fn.nota), coalesce(w.nota, w.conceito_id), -1))
É a mesma condição que é feita na tela de Lançamento de Conceitos, e ela está funcionando corretamente e no Listão não 
por isso que alterei

2023-03-13 18:20 UTC, rafalosiamcom requested changes

2023-03-13 18:20 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioNotasConceitosConsulta.cs
> +            var sql = $@"select coalesce(coalesce(coalesce(w.nota, fn.nota), coalesce(w.nota, w.conceito_id), -1))
Essa alteração não faz sentido Thiago, dessa forma nunca vai retornar o valor de uma que lança o conceito no fechamento

2023-03-14 12:13 UTC, rafalosiamcom approved these changes

2023-03-14 12:18 UTC, viniciusnyari approved these changes

2023-03-14 12:20 UTC, merged