Fix/91804
prefeiturasp/SME-NovoSGP pull request #12336
Opened 2023-04-18 16:06 UTC by julianocm

AB#91804

2023-04-18 16:08 UTC, Jailsvs approved these changes

2023-04-19 11:22 UTC, rafalosiamcom requested changes

2023-04-19 11:22 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/CompensacaoAusencia/SalvarCompensasaoAusenciaUseCase.cs
> +                periodo = consulta.Periodos.FirstOrDefault(p => p.Bimestre == bimestre);
Toda essa regra já existe no repositório de consulta do PeriodoEscolar que era chamado antes (ObterPeriodosEscolaresPorAnoEModalidadeTurmaQuery), não entendi porque trocar e implementar a regra aqui.
Regra de consulta do período escolar não deveria ficar no use case de salvamento da Compensação

2023-04-19 11:22 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/CompensacaoAusencia/SalvarCompensasaoAusenciaUseCase.cs
> +            }
Se o parâmetro pode bloquear o processo coloque a verificação dele antes de qualquer coisa, assim evita aquelas consultas de períodos de que não servirão se o processo for bloqueado aqui

2023-04-19 11:24 UTC, rafalosiamcom requested changes
Corrija o nome do UseCase para SalvarCompensacaoAusenciaUseCase

2023-04-19 18:32 UTC, rafalosiamcom approved these changes

2023-04-19 18:32 UTC, merged