Fix/88303 r2
prefeiturasp/SME-NovoSGP pull request #12619
Opened 2023-05-17 14:14 UTC by robsonamcom

2023-05-19 11:51 UTC, rafalosiamcom requested changes

2023-05-19 11:51 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusencia.cs
> +        public async Task<IEnumerable<CompensacaoAusenciaAlunoCalculoFrequenciaDto>> ObterTotalCompensacoesPorAlunosETurmaAsync(int bimestre, string turmaCodigo)
Essa consulta deveria esta no repositorioConsulta;
Também esta duplicado, pois ela já existe no RepositorioCompensacaoAusenciaAlunoConsulta

2023-05-19 11:51 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/CriaAtualizaCacheCompensacaoAusenciaTurmaBimestre/CriaAtualizaCacheCompensacaoAusenciaTurmaBimestreCommandHandler.cs
> +                .ObterTotalCompensacoesPorAlunosETurmaAsync(request.Bimestre, request.CodigoTurma);
fazer a consulta logo depois de Salvar vamos ter o mesmo problema com tempo de replicação que originou aquele Task.Delay la no UseCase;

2023-05-22 13:14 UTC, robsonamcom commented on src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/CriaAtualizaCacheCompensacaoAusenciaTurmaBimestre/CriaAtualizaCacheCompensacaoAusenciaTurmaBimestreCommandHandler.cs
> +                .ObterTotalCompensacoesPorAlunosETurmaAsync(request.Bimestre, request.CodigoTurma);
mesmo utilizando a conexão de escrita?
eu imagino que se estou consultando com a própria conexão que gravou as informações não tem tempo de delay.

2023-05-23 18:04 UTC, raphaeldiasrj commented on src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/CriaAtualizaCacheCompensacaoAusenciaTurmaBimestre/CriaAtualizaCacheCompensacaoAusenciaTurmaBimestreCommandHandler.cs
> +                .ObterTotalCompensacoesPorAlunosETurmaAsync(request.Bimestre, request.CodigoTurma);
Utilizando a conexão de escrita, isso não aconteceria. Mas estamos colocando no cache justamente para não ter que consultar na base quente. Sendo assim, isso não deveria ser lido da base antes de colocar no cache. Deve ir direto para o cache para que seja lido de lá.

Com a questão dos dados parciais que vc tem pra persistencia, vc resolve consultando os dados da base (de consulta) antes de fazer a persistencia da compensação e manda gravar a informação completa no cache.

2023-05-23 19:02 UTC, robsonamcom commented on src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/CriaAtualizaCacheCompensacaoAusenciaTurmaBimestre/CriaAtualizaCacheCompensacaoAusenciaTurmaBimestreCommandHandler.cs
> +                .ObterTotalCompensacoesPorAlunosETurmaAsync(request.Bimestre, request.CodigoTurma);
ok, vou seguir dessa forma e ajustar conciliando os dados que estão sendo gravados de compensação por vezes de forma parcial com as outras compensações já existentes na base para consolidar corretamente no cache para utilização no cálculo de frequência.

2023-06-09 18:07 UTC, robsonamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusencia.cs
> +        public async Task<IEnumerable<CompensacaoAusenciaAlunoCalculoFrequenciaDto>> ObterTotalCompensacoesPorAlunosETurmaAsync(int bimestre, string turmaCodigo)
Código atualizado conforme sugestão de revisão de PR.

2023-06-09 18:07 UTC, robsonamcom commented on src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/CriaAtualizaCacheCompensacaoAusenciaTurmaBimestre/CriaAtualizaCacheCompensacaoAusenciaTurmaBimestreCommandHandler.cs
> +                .ObterTotalCompensacoesPorAlunosETurmaAsync(request.Bimestre, request.CodigoTurma);
Código atualizado conforme sugestão de revisão de PR.

2023-06-16 11:03 UTC, rafalosiamcom requested changes

2023-06-16 11:03 UTC, rafalosiamcom commented on src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusencia.cs
> +        Task<IEnumerable<long>> ObterSemAlunoPorIds(long[] ids);
mover para o repositório de consulta

2023-06-16 11:33 UTC, robsonamcom commented on src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusencia.cs
> +        Task<IEnumerable<long>> ObterSemAlunoPorIds(long[] ids);
Função remanejada para o repositório de consulta. Foi remanejado somente o que foi criado para esse bug.

2023-07-12 17:13 UTC, merged