Story/88749
prefeiturasp/SME-NovoSGP pull request #12662
Opened 2023-05-22 17:53 UTC by thiiagofernando

2023-05-22 20:26 UTC, rafalosiamcom requested changes

2023-05-22 20:26 UTC, rafalosiamcom commented on src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpPendencias.cs
> +        public const string ExecutarAtualizacaoDosTotalizadoresDasPendencias = "sgp.atualizar.totalizadores.pendencia";
A rota no agendador é "pendencias" no plural

2023-05-22 20:26 UTC, rafalosiamcom commented on teste/SME.SGP.Aplicacao.Teste/CasosDeUso/Pendencias/CargaQuantidadeAulaDiaPendenciaUseCaseTeste.cs
> +            mediator.Verify(x => x.Send(It.IsAny<CargaPendenciasQuantidadeDiasQuantidadeAulasCommand>(), It.IsAny<CancellationToken>()), Times.Once);
Vc ta testando a chamada de um Command mocado, isso não testa nada.
Teste de integração deve ter os dados carregados na base, executar o método do repositório e conferir os dados alterados.

2023-05-22 20:26 UTC, rafalosiamcom commented on teste/SME.SGP.Aplicacao.Teste/CasosDeUso/Pendencias/CargaQuantidadeAulaDiaPendenciaUseCaseTeste.cs
> +            mediator.Verify(x => x.Send(It.IsAny<CargaPendenciasQuantidadeDiasQuantidadeAulasCommand>(), It.IsAny<CancellationToken>()), Times.Once);
Agora que vi que o teste ta no pacote de Testes Unitários.
Nesse caso se o UseCase não faz nada além de chamar o método do repositório não precisa de teste unitário, um teste de integração sim é necessário

2023-05-23 10:53 UTC, thiiagofernando commented on src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpPendencias.cs
> +        public const string ExecutarAtualizacaoDosTotalizadoresDasPendencias = "sgp.atualizar.totalizadores.pendencia";
ajustado

2023-05-23 10:53 UTC, thiiagofernando commented on teste/SME.SGP.Aplicacao.Teste/CasosDeUso/Pendencias/CargaQuantidadeAulaDiaPendenciaUseCaseTeste.cs
> +            mediator.Verify(x => x.Send(It.IsAny<CargaPendenciasQuantidadeDiasQuantidadeAulasCommand>(), It.IsAny<CancellationToken>()), Times.Once);
Criado testes de integração

2023-05-23 11:48 UTC, rafalosiamcom approved these changes

2023-05-23 11:58 UTC, merged