Story/92536
prefeiturasp/SME-NovoSGP pull request #13114
Opened 2023-08-09 17:44 UTC by DanylloAntunes

AB#92536
AB#100260

2023-08-09 18:21 UTC, viniciusnyari requested changes

2023-08-09 18:21 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Commands/RelatorioPAP/AbstractPersistenciaRelatorioPeriodicoRespostaPAPCommand.cs
> +    {
Sem validador

2023-08-09 18:23 UTC, DanylloAntunes commented on src/SME.SGP.Aplicacao/Commands/RelatorioPAP/AbstractPersistenciaRelatorioPeriodicoRespostaPAPCommand.cs
> +    {
E uma classe abstrata

2023-08-09 18:26 UTC, DanylloAntunes commented on src/SME.SGP.Aplicacao/Commands/RelatorioPAP/AlterarRelatorioPeriodicoQuestaoPAP/AlterarRelatorioPeriodicoQuestaoPAPCommand.cs
> +            RelatorioPeriodicoQuestao = relatorioPeriodicoQuestao;
incluído!

2023-08-09 18:27 UTC, DanylloAntunes commented on src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/SalvarRelatorioPAPUseCase.cs
> +                await mediator.Send(new SalvarRelatorioPeriodicoRespostaPAPCommand(questao.Resposta, questao.TipoQuestao, questaoExistente.Id));
Não tem pois para cada reposta e necessário fazer o mapeamento das resposta.

2023-08-10 11:41 UTC, Jailsvs approved these changes

2023-08-10 11:41 UTC, merged