102438 - Regra de negocio para não exigir objetico caso esteja no par…
prefeiturasp/SME-NovoSGP pull request #13260
Opened 2023-09-01 13:25 UTC by DanylloAntunes

AB#102438

2023-09-01 13:36 UTC, Jailsvs approved these changes

2023-09-05 12:04 UTC, rafalosiamcom requested changes

2023-09-05 12:04 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
> +            const int ANO_LETIVO = 2023;
Parametro Fixo 2023 ?

2023-09-05 12:13 UTC, rafalosiamcom requested changes

2023-09-05 12:13 UTC, rafalosiamcom commented on scripts/V649__PARAMETRO_OBJETIVOS_APRENDIZAGEM_PLANO_AULA_ANO_COMPONENTE.sql
> +            ('ObjetivosAprendizagemPlanoAulaAnoComponente', 108, 'Controle de obrigatóriedade de objetivos de aprendizagem para plano aula', '1322, 1770', 2023, true, now(), 'SISTEMA', null, null, '0
O nome do parametro não condiz com a função dele

2023-09-05 12:13 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
> +        private string[] _componentesObjetivosAprendizagemParametros;
nome de variavel fora de padrao

2023-09-05 12:14 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
> +        private string[] _componentesObjetivosAprendizagemParametros;
O nome também não condiz com a função dele

2023-09-05 12:18 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
> +            ObjetivosAprendizagemOpcionais = _componentesObjetivosAprendizagemParametros.Contains(disciplina.CodigoComponenteCurricular.ToString()) || consultasObjetivoAprendizagem.ComponentePossuiOb
Quando o ano não é 2023 essa referencia é nula e gera erro

2023-09-05 12:19 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
> +            if (parametro != null)
se não encontrar o parametro, caso a consulta seja anterioro a 2023, essa variavel vai ficar nula

2023-09-05 12:55 UTC, DanylloAntunes commented on src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
> +            const int ANO_LETIVO = 2023;
ajustado!

2023-09-05 12:55 UTC, DanylloAntunes commented on scripts/V649__PARAMETRO_OBJETIVOS_APRENDIZAGEM_PLANO_AULA_ANO_COMPONENTE.sql
> +            ('ObjetivosAprendizagemPlanoAulaAnoComponente', 108, 'Controle de obrigatóriedade de objetivos de aprendizagem para plano aula', '1322, 1770', 2023, true, now(), 'SISTEMA', null, null, '0
ajsutado!

2023-09-05 12:56 UTC, DanylloAntunes commented on src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
> +        private string[] _componentesObjetivosAprendizagemParametros;
ajustado!

2023-09-05 12:56 UTC, DanylloAntunes commented on src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
> +            ObjetivosAprendizagemOpcionais = _componentesObjetivosAprendizagemParametros.Contains(disciplina.CodigoComponenteCurricular.ToString()) || consultasObjetivoAprendizagem.ComponentePossuiOb
ajustado!

2023-09-05 12:56 UTC, DanylloAntunes commented on src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
> +            if (parametro != null)
ajustado!

2023-09-05 13:05 UTC, merged