Fix/104047 para Release 2 [Lançamento listão não reflete tela de notas]
prefeiturasp/SME-NovoSGP pull request #13391
Opened 2023-09-21 12:26 UTC by julianocm

AB#104047

2023-09-21 13:42 UTC, rafalosiamcom requested changes

2023-09-21 13:42 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
> +                await RemoverCache(string.Format(NomeChaveCache.FECHAMENTO_NOTA_TURMA_PERIODO_COMPONENTE, turma.Id, periodoEscolar.Id, fechamentoTurma.DisciplinaId), cancellationToken);
esta gravando essa chave ao salvar ?

2023-09-21 13:58 UTC, julianocm commented on src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
> +                await RemoverCache(string.Format(NomeChaveCache.FECHAMENTO_NOTA_TURMA_PERIODO_COMPONENTE, turma.Id, periodoEscolar.Id, fechamentoTurma.DisciplinaId), cancellationToken);
ela é salva somente ao obter os dados do fechamento turma

2023-09-21 14:06 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
> +                await RemoverCache(string.Format(NomeChaveCache.FECHAMENTO_NOTA_TURMA_PERIODO_COMPONENTE, turma.Id, periodoEscolar.Id, fechamentoTurma.DisciplinaId), cancellationToken);
salvar uma que temos cache devemos atualizar o mesmo, caso contrário a consulta seguinte sempre vai bater no banco e perder a vantagem de trabalharmos com cache

2023-09-21 19:16 UTC, julianocm commented on src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
> +                await RemoverCache(string.Format(NomeChaveCache.FECHAMENTO_NOTA_TURMA_PERIODO_COMPONENTE, turma.Id, periodoEscolar.Id, fechamentoTurma.DisciplinaId), cancellationToken);
verifiquei a rotina e não é possível atualizar os dados do cache pois ao salvar a informação temos somente os dados que foram modificados em tela, e o cache possui os lançamentos de todos os alunos da turma. com isso seria necessário realizar a consulta no banco para carregar os todos os dados no cache. que hoje só será carregado se acessar a tela novamente.

2023-09-22 21:14 UTC, rafalosiamcom approved these changes

2023-09-22 21:15 UTC, merged