Master -> release
prefeiturasp/SME-NovoSGP pull request #13633
Opened 2023-10-23 20:07 UTC by murilobarr0s

2023-10-23 20:16 UTC, GabrielVedolin approved these changes

2023-10-24 10:50 UTC, Dragondrax approved these changes

2023-10-24 11:20 UTC, Jailsvs requested changes

2023-10-24 11:20 UTC, Jailsvs commented on src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
> +                var disciplinasDtoNaoOrdenado = await repositorioComponenteCurricular.ObterDisciplinasPorIds(idsDisciplinas);
Este tratamento dará ruim para busca de info de componente território agrupado... Favor efetuar tratamento igual a pre prod:
![image](https://github.com/prefeiturasp/SME-NovoSGP/assets/33402817/eaa70246-f20d-4d5a-b19e-76deeb23a3e3)

2023-10-24 11:23 UTC, Jailsvs requested changes

2023-10-24 11:23 UTC, Jailsvs commented on src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
> +                    componentesCurriculares.ForEach(c =>
Não poderá mais fazer esta conversao para novo tratamento território... Ver como esta em pre prod

2023-10-24 12:12 UTC, Jailsvs approved these changes

2023-10-24 12:12 UTC, merged