Fix/107921 mstr
prefeiturasp/SME-NovoSGP pull request #13796
Opened 2023-11-16 20:11 UTC by robsonamcom

2023-11-16 20:16 UTC, Dragondrax requested changes

2023-11-16 20:16 UTC, Dragondrax commented on teste/SME.SGP.TesteIntegracao/ConsolidacaoConselhoDeClasse/ServicosFakes/ObterAlunosAtivosPorTurmaCodigoQueryHandlerFake.cs
> +        public async Task<IEnumerable<AlunoPorTurmaResposta>> Handle(ObterAlunosAtivosPorTurmaCodigoQuery request, CancellationToken cancellationToken)
Acho que é necessário adicionar um await ou remover o async desse método

2023-11-16 20:40 UTC, robsonamcom commented on teste/SME.SGP.TesteIntegracao/ConsolidacaoConselhoDeClasse/ServicosFakes/ObterAlunosAtivosPorTurmaCodigoQueryHandlerFake.cs
> +        public async Task<IEnumerable<AlunoPorTurmaResposta>> Handle(ObterAlunosAtivosPorTurmaCodigoQuery request, CancellationToken cancellationToken)
resolvido

2023-11-17 12:21 UTC, Dragondrax approved these changes

2023-11-17 13:57 UTC, merged