fix/118287 -> r2
prefeiturasp/SME-NovoSGP pull request #14402
Opened 2024-03-25 15:39 UTC by Dragondrax

AB#118287

2024-03-25 15:39 UTC, luizhpriotto commented
✅ Successfully linked to Azure Boards work item(s):
- [Bug 118287](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118287)

2024-03-25 15:39 UTC, luizhpriotto commented
✅ Successfully linked to Azure Boards work item(s):
- [Bug 118287](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118287)

2024-03-26 12:22 UTC, murilobarr0s requested changes

2024-03-26 12:22 UTC, murilobarr0s commented on src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQueryHandler.cs
> +                ues = await ObterUesPorUsuario(request.DreId, request.AnoLetivo, request.ConsideraHistorico, usuario);
Se o resultado de ues for null, aqui já irá descartar a ue inicializada na linha 33. O ideal para agrupar as ues do usuário, é um concat tratando antes se não é nulo, e depois até pode ter um distinct para não houver repetições. O que acha?

2024-03-26 13:20 UTC, murilobarr0s approved these changes

2024-03-26 13:20 UTC, merged