Story/106826
prefeiturasp/SME-NovoSGP pull request #14405
Opened 2024-03-25 18:05 UTC by DanylloAntunes

AB#106826

2024-03-25 18:05 UTC, luizhpriotto commented
✅ Successfully linked to Azure Boards work item(s):
- [User Story 106826](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106826)

2024-03-25 18:05 UTC, luizhpriotto commented
✅ Successfully linked to Azure Boards work item(s):
- [User Story 106826](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106826)

2024-03-25 20:16 UTC, rafalosiamcom requested changes
Story não precisa ir pra release, depois e liberar pre-prod para prod desce pre-prod para release

2024-03-26 11:24 UTC, rafalosiamcom approved these changes

2024-03-26 11:24 UTC, merged