AB#23486
prefeiturasp/SME-NovoSGP pull request #3793
Opened 2020-09-08 22:16 UTC by luizaraujoamcom

AB#23486
Mudanças relacionadas o método de salvar e também ao de exluir a notificação.

2020-09-09 18:06 UTC, rafalosiamcom requested changes

2020-09-09 18:06 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/CartaIntencoesObservacaoNotificacao/ExcluirNotificacaoCartaIntencoesObservacaoUseCase.cs
> +                await repositorioNotificacaoCartaIntencoesObservacao.Excluir(notificacao);
deveria usar uma transação pra garantir a exclusão dos 2 registros

2020-09-09 18:06 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/CartaIntencoes/Observacao/Excluir/ExcluirCartaIntencoesObservacaoCommandHandler.cs
> +
tinhamos falado no planejamento que se fosse executar a exclusão asincrona não seria possivel garantir uma transação para exclusão de todos os registros associados a entidade.
Ex: a exclusão de aula exclui também frequencia, plano de aula, notificações.. tudo dentro de uma transação

2020-09-11 14:14 UTC, luizaraujoamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/CartaIntencoesObservacaoNotificacao/ExcluirNotificacaoCartaIntencoesObservacaoUseCase.cs
> +                await repositorioNotificacaoCartaIntencoesObservacao.Excluir(notificacao);
Refatorado

2020-09-11 16:15 UTC, rafalosiamcom approved these changes

2020-09-11 16:15 UTC, merged