Ajuste sonar
prefeiturasp/SME-NovoSGP pull request #3978
Opened 2020-09-25 11:48 UTC by williamamcom

2020-09-25 12:06 UTC, rafalosiamcom requested changes

2020-09-25 12:06 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/RecuperacaoParalela/RelatorioRecuperacaoParalelaUseCase.cs
> +
remover codigo comentado

2020-09-25 12:06 UTC, rafalosiamcom commented on src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
> +                    //}
remover codigo comentado

2020-09-29 11:38 UTC, williamamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/RecuperacaoParalela/RelatorioRecuperacaoParalelaUseCase.cs
> +
Ajustado

2020-09-29 11:38 UTC, williamamcom commented on src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
> +                    //}
Ajustado

2020-10-28 01:36 UTC, closed without merging