feature/25386
prefeiturasp/SME-NovoSGP pull request #4088
Opened 2020-10-07 19:18 UTC by luizaraujoamcom

AB#24347

2020-10-07 19:57 UTC, rafalosiamcom requested changes

2020-10-07 19:57 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/PlanejamentoAnual/Copiar/MigrarPlanejamentoAnualCommandHandler.cs
> +                var checarTurma = await repositorioTurma.ObterPorId(turma);
Usar/criar querys para consulta dos dados de outros repositórios

2020-10-08 02:09 UTC, luizaraujoamcom commented on src/SME.SGP.Aplicacao/Commands/PlanejamentoAnual/Copiar/MigrarPlanejamentoAnualCommandHandler.cs
> +                var checarTurma = await repositorioTurma.ObterPorId(turma);
Realizei algumas alterações conforme conversamos hoje mais cedo. Favor verificar.

2020-10-08 15:50 UTC, rafalosiamcom requested changes

2020-10-08 15:50 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/PlanejamentoAnual/Copiar/MigrarPlanejamentoAnualCommandHandler.cs
> +                    throw new NegocioException($"Você não possui atribuição.");
essa mensagem tem que ser mais sugestiva pro usuário.. informar a turma e o componente que o usuário não tem atribuição

2020-10-08 15:50 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/PlanejamentoAnual/Copiar/MigrarPlanejamentoAnualCommandHandler.cs
> +                    throw new NegocioException($"Algum bimestre não está com o período aberto.");
o mesmo aqui, deve se informar o bimestre que não esta em aberto para o usuário saber qual ele deve solicitar a abertura para fazer os ajustes dele

2020-10-08 15:50 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/PlanejamentoAnual/Copiar/MigrarPlanejamentoAnualCommandHandler.cs
> +                await mediator.Send(new SalvarCopiaPlanejamentoAnualCommand(planejamentoCopiado));
As exceções devem ser levadas para fora do bloco de repetição da turma, para validar todas antes de retornar a exceção, assim nesse caso pode chamar o salvamento só quando não houver exceções carregadas
```suggestion
                if (!execoesEmAberto.Any() && !excecoesAtribuicao.Any())
                                await mediator.Send(new SalvarCopiaPlanejamentoAnualCommand(planejamentoCopiado));
```

2020-10-08 15:50 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/PlanejamentoAnual/Copiar/MigrarPlanejamentoAnualUseCase.cs
> +            var retorno = await mediator.Send(new MigrarPlanejamentoAnualCommand(dto));
Fazer rollback da transação no caso de uma exceção

2020-10-09 18:00 UTC, closed without merging