Correção Bug - Minhas pendências - Problemas no texto da pendência
prefeiturasp/SME-NovoSGP pull request #4461
Opened 2020-11-21 14:14 UTC by williamamcom

AB#28557

2020-11-21 14:17 UTC, luizaraujoamcom approved these changes

2020-11-21 14:51 UTC, rafalosiamcom requested changes

2020-11-21 14:51 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/PendenciaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivosCommandHandler.cs
> +            mensagem.AppendLine($"<i>Professor</i>: {aula.Professor}({aula.ProfessorRf})<br />");
No exemplo postado pelo Marlon esta assim
```suggestion
            mensagem.AppendLine($"<i>Componente Curricular: {componenteCurricular?.Nome ?? aula.DisciplinaId}</i><br />");
            mensagem.AppendLine($"<i>Professor: {aula.Professor}({aula.ProfessorRf})</i><br />");
```

2020-11-21 14:51 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs
> +            descricao.AppendLine($"<b>{pendencia.Instrucao}</b>");
Faltou incluir o bold também no método 
private string ObterDescricaoPendenciaGeral(Pendencia pendencia)

2020-11-21 15:24 UTC, rafalosiamcom approved these changes

2020-11-21 15:24 UTC, merged

2020-12-16 19:59 UTC, VitorFerragini commented on src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs
> +            descricao.AppendLine($"<b>{pendencia.Instrucao}</b>");
@rafalosiamcom essa pendência foi resolvida?