Feature/36684
prefeiturasp/SME-NovoSGP pull request #6101
Opened 2021-04-01 13:26 UTC by rgalante82

AB#36684

2021-04-01 13:55 UTC, luizaraujodev requested changes

2021-04-01 13:55 UTC, luizaraujodev commented on src/SME.SGP.Aplicacao/Commands/Sincronizacao/Ues/EnviarNotificacaoSincronizacaoUesInclusao/EnviarSincronizacaoEstruturaInstitucionalUesCommandHandler.cs
> +                var erro = new NegocioException($"_Não foi possível obter dados de estrutura institucional do EOL. {estruturaInstitucionalVigentePorDre?.Dres?.Count}");
```suggestion
                var erro = new NegocioException($"Não foi possível obter dados de estrutura institucional do EOL. {estruturaInstitucionalVigentePorDre?.Dres?.Count}");
```

2021-04-01 13:55 UTC, luizaraujodev commented on src/SME.SGP.Aplicacao/Queries/UE/ObterEstruturaInstitucionalVigente/ObterEstruturaInstitucionalVigenteQueryHandler.cs
> +                SentrySdk.AddBreadcrumb($"Ocorreu um erro na tentativa de buscar os dados de Estrutura Institucional Vigente por Dre: {request.CodigoDre} - HttpCode {resposta.StatusCode} - Body {resp
É necessário acionar o throw neste caso?

2021-04-05 18:55 UTC, rgalante82 commented on src/SME.SGP.Aplicacao/Queries/UE/ObterEstruturaInstitucionalVigente/ObterEstruturaInstitucionalVigenteQueryHandler.cs
> +                SentrySdk.AddBreadcrumb($"Ocorreu um erro na tentativa de buscar os dados de Estrutura Institucional Vigente por Dre: {request.CodigoDre} - HttpCode {resposta.StatusCode} - Body {resp
resolvido

2021-04-05 18:56 UTC, luizaraujodev approved these changes

2021-04-05 18:56 UTC, merged