Feature/38902
prefeiturasp/SME-NovoSGP pull request #6504
Opened 2021-05-05 18:41 UTC by williamamcom

2021-05-08 14:33 UTC, marcoslobo requested changes

2021-05-08 14:33 UTC, marcoslobo commented on src/SME.SGP.Api/Controllers/FechamentoAcompanhamentoTurmasController.cs
> +        public async Task<IActionResult> ListaTurmas([FromQuery] FiltroAcompanhamentoFechamentoTurmasDto filtro, [FromServices] IObterTurmasFechamentoAcompanhamentoUseCase useCase)
Esse endpoint poderia ter na sua rota o /turmas

2021-05-08 14:33 UTC, marcoslobo commented on src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
> +            var listarTodasTurmas = turmaId.Any(c => c == -99);
isso não seria responsabilidade do repositório. 
Mudar para o use case;

2021-05-10 13:28 UTC, williamamcom commented on src/SME.SGP.Api/Controllers/FechamentoAcompanhamentoTurmasController.cs
> +        public async Task<IActionResult> ListaTurmas([FromQuery] FiltroAcompanhamentoFechamentoTurmasDto filtro, [FromServices] IObterTurmasFechamentoAcompanhamentoUseCase useCase)
ok

2021-05-11 17:57 UTC, merged