fix/40933-master
prefeiturasp/SME-NovoSGP pull request #6889
Opened 2021-06-03 16:21 UTC by krisamcom

AB#40933

2021-06-03 16:29 UTC, marcoslobo requested changes

2021-06-03 16:29 UTC, marcoslobo commented on src/SME.SGP.Aplicacao/Queries/EOL/TurmaDisciplina/PodePersistirTurmaDisciplina/PodePersistirTurmaDisciplinaQueryHandler.cs
> +            var dataString = request.Data.ToString("s");
essa data poderia ser um tick;

2021-06-03 16:29 UTC, marcoslobo commented on src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs
> +                    componentesCurricularesDoProfessor = await mediator.Send(new ObterComponentesCurricularesQuePodeVisualizarHojeQuery(usuarioLogado, filtroAulasEventosCalendarioDto.TurmaCodigo));
Modificar o usuário logado para as propriedades que serão utilizadas na query ( perfil atual e RF ) ; 
Em outros pontos que poderá usar essa função, não é necessário Obter todo o objeto usuario logado(que é bem custoso)

2021-06-08 19:22 UTC, robsonamcom approved these changes

2021-06-08 20:07 UTC, marcoslobo approved these changes

2021-06-08 20:07 UTC, merged