Endpoint Integração SGP Calendário
prefeiturasp/SME-NovoSGP pull request #7527
Opened 2021-08-31 19:04 UTC by williamamcom

2021-09-04 15:10 UTC, marcoslobo requested changes

2021-09-04 15:10 UTC, marcoslobo commented on src/SME.SGP.Infra/Dtos/FiltroDiasLetivosPorUeEDataDTO.cs
> +        [Required(ErrorMessage = "A data de Inicio é obrigatória")]
início

2021-09-04 15:10 UTC, marcoslobo commented on src/SME.SGP.Infra/Dtos/FiltroDiasLetivosPorUeEDataDTO.cs
> +        [Required(ErrorMessage = "O codígo da escola é obrigatório")]
código

2021-09-04 15:10 UTC, marcoslobo commented on src/SME.SGP.Dominio/Enumerados/TipoTurno.cs
> +        manha = 1,
Manha; 
Todos estão com maisculo, menos este

2021-09-04 15:10 UTC, marcoslobo commented on src/SME.SGP.Dominio/Enumerados/TipoTurno.cs
> +        Nortuno = 3,
Noturno;

2021-09-04 16:57 UTC, rafalosiamcom commented on src/SME.SGP.Api/Controllers/IntegracoesController.cs
> +    public class IntegracoesController : ControllerBase
@marcoslobo existe o DiasLetivosCalendarioController mas não da pra Levar o método pra la porque ele tem o atributo Auhorize no controller.
Uma alternativa seria criar o controller de integração por assunto, como DiasLetivosCalendarioIntegracaoController
/api/v1/calendarios/integracao/dias-letivos

2021-09-06 13:02 UTC, rafalosiamcom requested changes

2021-09-06 13:02 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioTipoCalendario.cs
> +                modalidadeTipoCalendarioId,
```suggestion
                modalidadeTipoCalendarioId = (int)modalidadeTipoCalendarioId,
```

2021-09-06 14:14 UTC, rafalosiamcom approved these changes

2021-09-06 14:14 UTC, merged