fix/48404-r2
prefeiturasp/SME-NovoSGP pull request #7529
Opened 2021-08-31 20:04 UTC by krisamcom

AB#48404

2021-08-31 20:19 UTC, rafalosiamcom requested changes

2021-08-31 20:19 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
> +        private readonly IRepositorioComponenteCurricular repositorioComponenteCurricular;
UseCases não devem acessar repositório, deve utilizar ou criar uma query e fazer uso do mediator

2021-08-31 23:08 UTC, krisamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
> +        private readonly IRepositorioComponenteCurricular repositorioComponenteCurricular;
corrigido

2021-09-01 11:28 UTC, robsonamcom approved these changes

2021-09-01 11:37 UTC, rafalosiamcom approved these changes

2021-09-01 11:37 UTC, merged