Feature/52257
prefeiturasp/SME-NovoSGP pull request #8036
Opened 2021-10-30 18:10 UTC by viniciusnyari

AB#52257

2021-10-30 18:58 UTC, williamamcom commented on src/SME.SGP.Dominio.Servicos/ServicoFechamentoReabertura.cs
> +                fechamentoReabertura.Bimestres.ToList().ForEach(f => f.FechamentoAbertura = null);
Retirar comentário

2021-10-30 19:01 UTC, williamamcom commented on src/SME.SGP.Dominio.Servicos/ServicoFechamentoReabertura.cs
> +                fechamentoReabertura.Bimestres.ToList().ForEach(f => f.FechamentoAbertura = null);
Retirar comentário

2021-10-30 19:06 UTC, williamamcom commented on src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
>                  canalRabbit.QueueDeclare(fila, true, false, false, args);
Não vai mais precisar desse trecho comentado ?

2021-10-30 19:09 UTC, williamamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaSMEUseCase.cs
> +                                           Tipo de calendário: {fechamentoReabertura.TipoCalendario.Nome} <br/>
ajustar (período)

2021-10-30 22:58 UTC, rafalosiamcom requested changes

2021-10-30 22:58 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaUseCase.cs
> +                    var adminsSgpUe = servicoEOL.ObterAdministradoresSGP(fechamentoReabertura.Ue.CodigoUe).Result;
```suggestion
                    var adminsSgpUe = await servicoEOL.ObterAdministradoresSGP(fechamentoReabertura.Ue.CodigoUe);
```

2021-10-30 22:58 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaSMEUseCase.cs
> +                var adminsSgpDre = servicoEOL.ObterAdministradoresSGP(filtro.Dre).Result;
```suggestion
                var adminsSgpDre = await servicoEOL.ObterAdministradoresSGP(filtro.Dre);
```

2021-10-30 22:58 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaSMEUseCase.cs
> +                    var adminsSgpUe = servicoEOL.ObterAdministradoresSGP(ue).Result;
```suggestion
                    var adminsSgpUe = await servicoEOL.ObterAdministradoresSGP(ue);
```

2021-10-30 22:58 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaSMEUseCase.cs
> +                }
esse código todo esta duplicado nos 2 use cases.
Devemos criar um command para aproveitar o mesmo código, ou até mesmo utilizar a fica de processamento por UE e usar nos 2 casos

2021-10-30 23:12 UTC, viniciusnyari commented on src/SME.SGP.Dominio.Servicos/ServicoFechamentoReabertura.cs
> +                fechamentoReabertura.Bimestres.ToList().ForEach(f => f.FechamentoAbertura = null);
Removido

2021-10-30 23:13 UTC, viniciusnyari commented on src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
>                  canalRabbit.QueueDeclare(fila, true, false, false, args);
Isso foi feito por outro DEV

2021-10-30 23:14 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaSMEUseCase.cs
> +                                           Tipo de calendário: {fechamentoReabertura.TipoCalendario.Nome} <br/>
Ajustado.

2021-10-31 03:09 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaUseCase.cs
> +                    var adminsSgpUe = servicoEOL.ObterAdministradoresSGP(fechamentoReabertura.Ue.CodigoUe).Result;
Ajustado

2021-10-31 03:09 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaSMEUseCase.cs
> +                var adminsSgpDre = servicoEOL.ObterAdministradoresSGP(filtro.Dre).Result;
Ajustado

2021-10-31 03:10 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaSMEUseCase.cs
> +                    var adminsSgpUe = servicoEOL.ObterAdministradoresSGP(ue).Result;
Ajustado

2021-10-31 03:10 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaSMEUseCase.cs
> +                }
Transformado em um único command

2021-11-01 11:08 UTC, rafalosiamcom requested changes

2021-11-01 11:08 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/Notificacao/ExecutaNotificacaoFechamentoReabertura/ExecutaNotificacaoFechamentoReaberturaCommandHandler.cs
> +            foreach (var ue in ues)
A execução continua sincrona.
Como comentado anteriormente, para cada UE deve ser enviada uma mensagem para uma fila especifica para executar a notificação para essa UE.
Assim cada mensagem processa apenas 1 UE.

Não podemos deixar processos muito longos executando em uma unica mensagem no rabbit

2021-11-01 11:58 UTC, williamamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaSMEUseCase.cs
> +        public NotificarFechamentoReaberturaSMEUseCase(IMediator mediator, IServicoUsuario servicoUsuario,
se não tiver usando IServicoEol, IServicoUsuario, retirar da injeção de dependência

2021-11-01 12:11 UTC, williamamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaUseCase.cs
> +        {
se não tiver usando IServicoEol, IServicoUsuario, retirar da injeção de dependência

2021-11-01 12:12 UTC, williamamcom commented on src/SME.SGP.Aplicacao/Commands/Notificacao/ExecutaNotificacaoFechamentoReabertura/ExecutaNotificacaoFechamentoReaberturaCommand.cs
> +    }
Ajustar para -> public IEnumerable<string> UesCodigo { get; set; }

2021-11-01 12:15 UTC, williamamcom commented on src/SME.SGP.Infra/Dtos/Fechamento/FiltroNotificacaoFechamentoReaberturaSMEDto.cs
> +        public FechamentoReabertura FechamentoReabertura{ get; set; }
public IEnumerable<string> UesCodigo { get; set; }

2021-11-01 21:07 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Commands/Notificacao/ExecutaNotificacaoFechamentoReabertura/ExecutaNotificacaoFechamentoReaberturaCommandHandler.cs
> +            foreach (var ue in ues)
Ajustado.

2021-11-01 21:08 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaUseCase.cs
> +        {
Ajustado

2021-11-01 21:08 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaSMEUseCase.cs
> +        public NotificarFechamentoReaberturaSMEUseCase(IMediator mediator, IServicoUsuario servicoUsuario,
Ajustado.

2021-11-01 21:11 UTC, williamamcom approved these changes

2021-11-01 21:11 UTC, merged