52754 - Manutenção no cadastro de pendência
prefeiturasp/SME-NovoSGP pull request #8096
Opened 2021-11-08 19:13 UTC by murilobarr0s

AB#52754

2021-11-08 20:47 UTC, rafalosiamcom requested changes

2021-11-08 20:47 UTC, rafalosiamcom commented on scripts/V504__INCLUSAO_CAMPO_UEID_TABELA_PENDENCIA.sql
> +ALTER TABLE public.pendencia ADD ue_id int8;
a referencia tem que ser opcional, pois nem todas as pendências são de perfis de UE, algumas são do professor por exemplo

2021-11-08 20:47 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/PendenciaUsuario/RelacionaPendenciaUsuario/RelacionaPendenciaUsuarioCommandHandler.cs
> +                                break;
Nível na pendencia ?
Não entendi. o workflow tem Nível porque a tem que ser aprovado por um nivel para enviar para o próximo.
Não vejo como aplicar esse comportamento nas pendências.

2021-11-08 20:47 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/PendenciaUsuario/SalvarPendenciaUsuario/SalvarPendenciaUsuarioCommandHandler.cs
> +        public SalvarPendenciaUsuarioCommandHandler(IMediator mediator, IRepositorioPendenciaUsuario repositorioPendenciaUsuario, IRepositorioPendenciaPerfil repositorioPendenciaPerfil)
Vai usar o mesmo command para salvar pendencia de usuario ou nível ?
não seria melhor renomear para não relacionar o nome apenas a pendencia_usuario ?

2021-11-08 20:47 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/PendenciaUsuario/SalvarPendenciaUsuario/SalvarPendenciaUsuarioCommandHandler.cs
> +                //cria command de vinculo da pendência com usuário
esse vai ser criado em outra tarefa ?

2021-11-08 20:47 UTC, rafalosiamcom commented on src/SME.SGP.Dominio/Enumerados/PerfilUsuario.cs
> +        PERFIL_COMUNICADOS_UE = 21,
não fica redundante o prefixo PERFIL_ se o enum já é PerfilUsuario ?

2021-11-08 20:50 UTC, murilobarr0s commented on src/SME.SGP.Aplicacao/Commands/PendenciaUsuario/SalvarPendenciaUsuario/SalvarPendenciaUsuarioCommandHandler.cs
> +                //cria command de vinculo da pendência com usuário
sim

2021-11-08 20:56 UTC, murilobarr0s commented on scripts/V504__INCLUSAO_CAMPO_UEID_TABELA_PENDENCIA.sql
> +ALTER TABLE public.pendencia ADD ue_id int8;
ajustado

2021-11-08 20:58 UTC, murilobarr0s commented on src/SME.SGP.Dominio/Enumerados/PerfilUsuario.cs
> +        PERFIL_COMUNICADOS_UE = 21,
ajustado

2021-11-08 21:02 UTC, murilobarr0s commented on src/SME.SGP.Aplicacao/Commands/PendenciaUsuario/RelacionaPendenciaUsuario/RelacionaPendenciaUsuarioCommandHandler.cs
> +                                break;
Fiz esse nível para não se aplicar em aprovação, e sim, em encaminhamentos previstos nessa story seguinte: 50651

- tocando principalmente os itens (1.2 e 1.2.1)

2021-11-08 21:04 UTC, murilobarr0s commented on src/SME.SGP.Aplicacao/Commands/PendenciaUsuario/SalvarPendenciaUsuario/SalvarPendenciaUsuarioCommandHandler.cs
> +        public SalvarPendenciaUsuarioCommandHandler(IMediator mediator, IRepositorioPendenciaUsuario repositorioPendenciaUsuario, IRepositorioPendenciaPerfil repositorioPendenciaPerfil)
irei usar o mesmo command para salvar a pendencia perfil, mas a questão da pendencia perfil usuário será disparada para dentro do command de pendencia usuário, como previsto após salvar a entidade de pendencia perfil.

2021-11-09 12:06 UTC, rafalosiamcom approved these changes

2021-11-09 12:06 UTC, merged