Feature/52759
prefeiturasp/SME-NovoSGP pull request #8194
Opened 2021-11-22 14:26 UTC by viniciusnyari

AB#52759

2021-11-22 15:53 UTC, rafalosiamcom requested changes

2021-11-22 15:53 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverAtribuicaoPendenciasUsuariosUeUseCase.cs
> +                await mediator.Send(new SalvarLogViaRabbitCommand($"Erro na remoção de atribuição de Pendência Perfil Usuário por UE.", LogNivel.Negocio, LogContexto.Pendencia, ex.Message));
deve subir a exceção para que a mensagem caia na deadletter e o problema possa ser corrigido

2021-11-22 15:53 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverAtribuicaoPendenciasUsuariosUeUseCase.cs
> +                    }
acredito que esse tratamento deva estar em outra fila, porque dessa forma se ocorrer erro em apenas 1 dessas atribuições a mensagem que cai na deadletter vai ser a de tratar toda a UE.
Assim o reprocessamento dela vai passar pelo tratamento de todas as atribuições novamente.

Devemos fazer o processo mais pontual, para que se 1 deles de erro, seja reprocessado somente esse item

2021-11-22 15:53 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverAtribuicaoPendenciasUsuariosUeUseCase.cs
> +        }
esses 2 métodos são usados em outro command também, não é melhor gerar uma Query Mediator para ser reaproveitado ?

2021-11-22 17:08 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverAtribuicaoPendenciasUsuariosUeUseCase.cs
> +        }
Transformado em EnunHelper os que são passados por tipos primitivos e os demais transformados em extension methods.

2021-11-22 17:49 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverAtribuicaoPendenciasUsuariosUeUseCase.cs
> +                    }
Criado uma nova fila.

2021-11-22 17:58 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverAtribuicaoPendenciasUsuariosUeUseCase.cs
> +                await mediator.Send(new SalvarLogViaRabbitCommand($"Erro na remoção de atribuição de Pendência Perfil Usuário por UE.", LogNivel.Negocio, LogContexto.Pendencia, ex.Message));
Feito.

2021-11-23 11:34 UTC, rafalosiamcom approved these changes

2021-11-23 11:35 UTC, merged