Notificação de Compensação Extemporânea e alterado o salvar
prefeiturasp/SME-NovoSGP pull request #8204
Opened 2021-11-23 19:31 UTC by thiiagofernando

AB#53774
AB#53775

2021-11-23 19:40 UTC, luizcarloscezario approved these changes

2021-11-23 19:59 UTC, rafalosiamcom requested changes

2021-11-23 19:59 UTC, rafalosiamcom commented on src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
> +            var parametroAtivo = await mediator.Send(new ObterParametroSistemaPorTipoQuery(TipoParametroSistema.PermiteCompensacaoForaPeriodo));
Deve ser informado o ano para consulta do parametro

2021-11-23 19:59 UTC, rafalosiamcom commented on src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
> +            return gerarNotificacao;
Ajustar a condição do retorno;
Se ambas periodoAberto e parametroAtivo estiverem false deve gerar uma exceção para não salvar o registro

2021-11-23 20:04 UTC, rafalosiamcom requested changes

2021-11-23 20:04 UTC, rafalosiamcom commented on src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
> +            servicoNotificacao.Salvar(notificacao);
Não utilizar o servicoNotificacao.
Usar o EnviarNotificacaoCommand que recebe uma lista de cargos, dessa forma não precisa buscar os gestores para notificar

2021-11-24 11:42 UTC, thiiagofernando commented on src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
> +            var parametroAtivo = await mediator.Send(new ObterParametroSistemaPorTipoQuery(TipoParametroSistema.PermiteCompensacaoForaPeriodo));
Alterado para ObterParametroSistemaPorTipoEAnoQuery

2021-11-24 11:42 UTC, thiiagofernando commented on src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
> +            servicoNotificacao.Salvar(notificacao);
alterado para o EnviarNotificacaoCommand

2021-11-24 11:43 UTC, thiiagofernando commented on src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
> +            return gerarNotificacao;
ajustado a condição para gerar uma exceção

2021-11-24 11:57 UTC, rafalosiamcom approved these changes

2021-11-24 11:57 UTC, rafalosiamcom commented on src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
> +                     turma.ModalidadeCodigo.ObterAtributo<DisplayAttribute>().ShortName,
Existe uma extensão pra isso
```suggestion
                     turma.ModalidadeCodigo.ObterNomeCurto(),
```

2021-11-24 11:57 UTC, rafalosiamcom commented on src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
> +                return false;
Se não entrar na primeira condição já quer dizer que o periodo não esta aberto, não precisa checar novamente por causa do else
```suggestion
            else if (parametroAtivo)
                return true;
            else
                throw new NegocioException("Compensação de ausência não permitida, É necessário que o período esteja aberto");
```

2021-11-24 11:57 UTC, rafalosiamcom commented on src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
> +            return false;
```suggestion
```

2021-11-24 12:05 UTC, thiiagofernando commented on src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
> +            return false;
Alterado para ObterNomeCurto

2021-11-24 12:06 UTC, merged