Alterar consultar para base réplica
prefeiturasp/SME-NovoSGP pull request #8381
Opened 2021-12-20 20:16 UTC by viniciusnyari

AB#55547

2021-12-21 13:53 UTC, marcoslobo reviewed
Criar um novo repositório para repositório para consultas não é o ideal, poderia ser resolvido dentro do repositório com um contexto só para consulta;
https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs

2021-12-21 14:00 UTC, marcoslobo requested changes

2021-12-21 17:14 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaFrequenciaPorAula/ObterListaFrequenciaPorAulaQuery.cs
> +                .WithMessage("a aula deve ser informada.");
Ajustado.

2021-12-22 17:35 UTC, rafalosiamcom approved these changes

2021-12-22 17:35 UTC, merged