Adicionado QueryName
prefeiturasp/SME-NovoSGP pull request #8734
Opened 2022-02-04 18:26 UTC by thiiagofernando

AB#58309
AB#58336

2022-02-04 18:36 UTC, rafalosiamcom requested changes

2022-02-04 18:36 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
> +            var result = (await database.Conexao.QueryAsync<AbrangenciaTurmaRetorno>(query.ToString(), new { login, perfil, consideraHistorico, modalidade, semestre = periodo, codigoUe, anoLetivo, ti
o nome da query não pode ser muito extenso pois não vai aparecer no grafico dessa forma. Utilize só o nome da query e não o repositorio

2022-02-18 11:27 UTC, thiiagofernando commented on src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
> +            var result = (await database.Conexao.QueryAsync<AbrangenciaTurmaRetorno>(query.ToString(), new { login, perfil, consideraHistorico, modalidade, semestre = periodo, codigoUe, anoLetivo, ti
alterado

2022-03-04 13:08 UTC, rafalosiamcom approved these changes

2022-03-04 13:09 UTC, merged