Story/51799 -> release
prefeiturasp/SME-NovoSGP pull request #8994
Opened 2022-03-18 19:10 UTC by murilobarr0s

AB#60252

2022-03-18 19:59 UTC, raphaeldiasrj requested changes
Anotei 5 pontos ao longo do código, verifica pra gente, por favor

2022-03-18 19:59 UTC, raphaeldiasrj commented on src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
> +            if (dreId == 0 && ueId == 0)
Este if faz a mesma coisa do if de baixo e o ternário também faz a mesma coisa nas duas pontas. Favor verificar e reescrever este bloco visando redução de código e reaproveitamento.

2022-03-18 19:59 UTC, raphaeldiasrj commented on teste/SME.SGP.Aplicacao.Teste/CasosDeUso/DashboardDiarioBordo/ObterQuantidadeTotalDeDiariosPreenchidosEPendentesPorAnoTurmaUseCaseTeste.cs
> +            bool validaComTurma = !Regex.IsMatch(dadosGrafico?.FirstOrDefault().TurmaAno, @"^[0-9]+$");
Favor fazer a validação com uma informação específica e legível ao invés de usar Regex. Por exemplo Assert.Equals(dadosGrafico?.FirstOrDefault().TurmaAno, 2022)

2022-03-18 19:59 UTC, raphaeldiasrj commented on teste/SME.SGP.Aplicacao.Teste/CasosDeUso/DashboardDiarioBordo/ObterQuantidadeTotalDeDiariosPreenchidosEPendentesPorAnoTurmaUseCaseTeste.cs
> +            bool validaComTurma = Regex.IsMatch(dadosGrafico?.FirstOrDefault().TurmaAno, @"^[0-9]+$");
Favor fazer a validação com uma informação específica e legível ao invés de usar Regex. Por exemplo Assert.Equals(dadosGrafico?.FirstOrDefault().TurmaAno, 2022)

2022-03-18 19:59 UTC, raphaeldiasrj commented on teste/SME.SGP.Aplicacao.Teste/CasosDeUso/DashboardDiarioBordo/ObterQuantidadeTotalDeDiariosPreenchidosEPendentesPorAnoTurmaUseCaseTeste.cs
> +            Assert.True(verificaSePossuiSoNumeros);
O titulo do teste me dá a entender que devem trazer os dados da visão UE, mas o Assert dele está testando outra coisa completamente diferente.

2022-03-18 19:59 UTC, raphaeldiasrj commented on teste/SME.SGP.Aplicacao.Teste/CasosDeUso/DashboardDiarioBordo/ObterQuantidadeTotalDeDiariosPreenchidosEPendentesPorAnoTurmaUseCaseTeste.cs
> +            bool verificaSePossuiSoNumeros = Regex.IsMatch(dadosGrafico?.FirstOrDefault().TurmaAno, @"^[0-9]+$");
O titulo do teste me dá a entender que devem trazer os dados da visão DRESME, mas o Assert dele está testando outra coisa completamente diferente.

2022-03-18 20:49 UTC, raphaeldiasrj commented on src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
> +            if (dreId == 0 && ueId == 0)
Apenas um adendo, encontrei minúsculas diferenças entre os ifs. Conseguimos colocar tudo num StringBuilder e controlar melhor isso

2022-03-18 21:33 UTC, murilobarr0s commented on src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
> +            if (dreId == 0 && ueId == 0)
ajustado!

2022-03-21 11:53 UTC, raphaeldiasrj approved these changes

2022-03-21 12:41 UTC, merged