Feature/60158
prefeiturasp/SME-NovoSGP pull request #9033
Opened 2022-03-23 14:54 UTC by viniciusnyari

AB#60158

2022-03-23 19:14 UTC, rafalosiamcom requested changes

2022-03-23 19:40 UTC, viniciusnyari commented on scripts/V531__INCLUIR_NOTA_CONCEITO_COMPONENTE_CURRICULAR_CONSOLIDACAO_TURMA_ALUNO.sql
> +alter table consolidado_conselho_classe_aluno_turma add column componente_curricular_id int8 NULL;
Conforme alinhamento, vamos colocar em uma tabela auxiliar.

2022-03-23 19:41 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/PersistirParecerConclusivoCommand/PersistirParecerConclusivoCommandHandler.cs
> +            var aluno = (await mediator.Send(new ObterAlunosEolPorCodigosEAnoQuery(new long[] { long.Parse(conselhoClasse.AlunoCodigo) }, request.AnoLetivo))).FirstOrDefault();
OK

2022-03-23 19:43 UTC, viniciusnyari commented on src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoConsulta.cs
> +            return await database.Conexao.QueryFirstOrDefaultAsync<ConselhoClasseAluno>(query, new { conselhoClasseAlunoId });
Resolvido

2022-03-24 15:34 UTC, rafalosiamcom commented on scripts/V531__INCLUIR_NOTA_CONCEITO_COMPONENTE_CURRICULAR_CONSOLIDACAO_TURMA_ALUNO.sql
> +componente_curricular_id int8 NULL,
incluir FK nesse no componente_curricular também

2022-03-24 15:34 UTC, rafalosiamcom commented on scripts/V531__INCLUIR_NOTA_CONCEITO_COMPONENTE_CURRICULAR_CONSOLIDACAO_TURMA_ALUNO.sql
> +REFERENCES public.consolidado_conselho_classe_aluno_turma(id);
falta incluir indices nas FKs

2022-03-24 15:34 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
> +            unitOfWork.IniciarTransacao();
acho que não precisa de transação nesse caso, pois a consolidação será disparada com bastante frequencia e depois de abrir a transação esta fazendo consultas no banco, tornando a transação muito longa e deixando outras transações em lock no banco

2022-03-24 17:59 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Commands/ConsolidacaoNotaAlunoCommand/ConsolidacaoNotaAlunoCommandHandler.cs
> +            var aluno = (await mediator.Send(new ObterAlunosEolPorCodigosEAnoQuery(new long[] { long.Parse(request.AlunoCodigo) }, request.AnoLetivo))).FirstOrDefault();
Feito

2022-03-24 18:01 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/PersistirParecerConclusivoCommand/PersistirParecerConclusivoCommandHandler.cs
> +            var aluno = (await mediator.Send(new ObterAlunosEolPorCodigosEAnoQuery(new long[] { long.Parse(conselhoClasse.AlunoCodigo) }, request.AnoLetivo))).FirstOrDefault();
Feito

2022-03-24 18:03 UTC, viniciusnyari commented on scripts/V531__INCLUIR_NOTA_CONCEITO_COMPONENTE_CURRICULAR_CONSOLIDACAO_TURMA_ALUNO.sql
> +componente_curricular_id int8 NULL,
OK

2022-03-24 18:08 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
> +            unitOfWork.IniciarTransacao();
OK

2022-03-24 18:11 UTC, viniciusnyari commented on scripts/V531__INCLUIR_NOTA_CONCEITO_COMPONENTE_CURRICULAR_CONSOLIDACAO_TURMA_ALUNO.sql
> +REFERENCES public.consolidado_conselho_classe_aluno_turma(id);
Feito

2022-03-24 19:42 UTC, merged