Story/60120 -> Release
prefeiturasp/SME-NovoSGP pull request #9060
Opened 2022-03-25 13:11 UTC by FernandoGroeler

AB#60120

2022-03-25 13:32 UTC, rafalosiamcom requested changes
Esta faltando os testes

2022-03-25 13:32 UTC, rafalosiamcom commented on src/SME.SGP.Api/Controllers/FechamentoTurmaController.cs
> +        [HttpPost("consolidar-fechamento")]
consolidação de fechamento nessa história ?

2022-03-29 14:57 UTC, FernandoGroeler commented on src/SME.SGP.Api/Controllers/FechamentoTurmaController.cs
> +        [HttpPost("consolidar-fechamento")]
Conversamos que as alterações devem estar na release também, portanto, não haveria problema.

2022-03-29 15:16 UTC, rafalosiamcom requested changes

2022-03-29 15:28 UTC, FernandoGroeler commented on teste/SME.SGP.Aplicacao.Teste/Queries/ObterMatriculasAlunoNaUEQueryHandlerTeste.cs
> +            var resposta = await httpClient.GetAsync("https://api.eol.com.br/somefakeurl");
O "SendAsync" é um método protegido que é executado ao executar o HTTP cliente.
Normalmente se usa uma interface para "simular", no entanto, não há interface HttpClient. Em vez disso, a capacidade de substituir sua funcionalidade esta dentro de uma classe abstrata (HttpMessageHandler). Essa classe pode ser injetada no HttpCliente permitindo substituir qualquer solicitação.
Como o MessageHandler é abstrato, é necessário criar uma implementação. O SendAsync não tem relação com o método enviado pelo HttpClient (SendAsync, GetAsync), é a implementação abstrata do HttpResponseMessage que é executada nas requisições.

2022-03-29 15:30 UTC, FernandoGroeler commented on teste/SME.SGP.Aplicacao.Teste/Queries/ObterMatriculasAlunoNaUEQueryHandlerTeste.cs
> +            }
Pergunta: A query é executada em outro projeto API EOL. Se a query foi feita lá, não seria lá o teste unitário do retorno efetivo da query e no SGP o teste não deveria prever que a query retornou "corretamente" e executar o teste da operação realizada de forma posterior?

2022-03-30 12:24 UTC, rafalosiamcom approved these changes

2022-03-30 12:24 UTC, rafalosiamcom commented on teste/SME.SGP.Aplicacao.Teste/Queries/ObterMatriculasAlunoNaUEQueryHandlerTeste.cs
> +            Assert.True(retorno.Any(), "Existe encaminhamento AEE vigente.");
a mensagem do acerte é exibido no caso de o assert falhar.
Se a query se chama ObterMatriculasAlunoNaUE no caso de falhar a mensagem seria "Falha ao consultar matriculas do aluno no EOL"

2022-03-30 12:28 UTC, merged