Correção da consolidação de notas (conselho de classe e fechamento nota)
prefeiturasp/SME-NovoSGP pull request #9114
Opened 2022-03-30 20:32 UTC by viniciusnyari

Correção da consolidação de notas (conselho de classe e fechamento nota)

2022-03-30 21:07 UTC, rafalosiamcom requested changes

2022-03-30 21:07 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidado.cs
> +			                               coalesce(fn.disciplina_id, comp.id) DisciplinaId,
o join entre as tabelas desses 2 campos é "ON comp.id = fn.disciplina_id"
então esse coalesce não muda nada porque sempre vão ser iguais

2022-03-30 21:13 UTC, viniciusnyari commented on src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidado.cs
> +			                               coalesce(fn.disciplina_id, comp.id) DisciplinaId,
Justo, no segundo select ele vinha nulo. Troquei pelo componente_cucrricular que vem sempre

2022-04-01 00:42 UTC, rafalosiamcom approved these changes

2022-04-01 00:42 UTC, merged