adicionado 2 novos endpoints no ConselhoClasseController para obter t…
prefeiturasp/SME-NovoSGP pull request #9253
Opened 2022-04-20 19:58 UTC by danilosoad

AB#61260

2022-04-21 20:35 UTC, rafalosiamcom requested changes
Faltou os testes de integração para garantir o funcionamento dos endpoints

2022-04-21 20:35 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
> +                        join componente_curricular cc on cc.id = cast( fa.disciplina_id as bigint )
Acredito não ser necessário a descrição no retorno desse endpoint então pode remover o join com componente_curricular e ganhamos mais performance

2022-04-21 20:35 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
> +                        join componente_curricular cc on cc.id = a.disciplina_id::int8
remover a descrição e o Join

2022-04-21 20:35 UTC, rafalosiamcom commented on teste/SME.SGP.Aplicacao.Teste/CasosDeUso/ConselhodeClasse/ObterTotalAulasPorAlunoTurmaUseCaseTeste.cs
> +                                .ReturnsAsync(new List<TotalAulasPorAlunoTurmaDto>());
a unica coisa que esse useCase faz é chamar a ObterTotalAulasPorAlunoTurmaQuery.
Vc ta mocando a chamada da query e testando aqui se o retorno não é nulo, isso não serve pra nada.
O ideial aqui é ter um teste de integração que vai executar a consulta na base e garantir que o useCase retorne a informação esperada

2022-04-21 20:35 UTC, rafalosiamcom commented on teste/SME.SGP.Aplicacao.Teste/CasosDeUso/ConselhodeClasse/ObterTotalAulasSemFrequenciaPorTurmaUseCaseTeste.cs
> +            Assert.NotNull(totalAulasSemFrequencia);
mesmo caso do teste anterior

2022-04-25 11:36 UTC, rafalosiamcom requested changes
O teste de integração não é esse, é o que o Raphael Dias apresentou pra gente.
Tem o exemplo dele no projeto SME.SGP.TesteIntegracao

2022-04-26 04:08 UTC, danilosoad commented on src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
> +                        join componente_curricular cc on cc.id = a.disciplina_id::int8
foi preciso do join para verificar os componentes curriculares que não permitem registro de frequencia

2022-04-26 12:05 UTC, viniciusnyari requested changes

2022-04-26 12:05 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterTotalAulasPorAlunoTurmaUseCase.cs
> +namespace SME.SGP.Aplicacao.CasosDeUso.ConselhoClasse
O namespace vai só até Aplicacao

2022-04-26 12:05 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterTotalAulasSemFrequenciaPorAlunoTurmaUseCase.cs
> +namespace SME.SGP.Aplicacao.CasosDeUso.ConselhoClasse
Aqui também

2022-04-26 12:05 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConselhoClasse/IObterTotalAulasPorAlunoTurmaUseCase.cs
> +namespace SME.SGP.Aplicacao.Interfaces.CasosDeUso.ConselhoClasse
Aqui também o namespace

2022-04-26 12:05 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConselhoClasse/IObterTotalAulasSemFrequenciaPorAlunoTurmaUseCase.cs
> +namespace SME.SGP.Aplicacao.Interfaces.CasosDeUso.ConselhoClasse
Esse tbém

2022-04-26 12:05 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterTotalAlunosSemFrequenciaPorTurmaQuery/ObterTotalAulasSemFrequenciaPorTurmaQuery.cs
> +namespace SME.SGP.Aplicacao.Queries.ConselhoClasse.ObterTotalAlunosSemFrequenciaPorTurmaQuery
Esse também, só até aplicação

2022-04-26 12:05 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterTotalAlunosSemFrequenciaPorTurmaQuery/ObterTotalAulasSemFrequenciaPorTurmaQueryHandler.cs
> +namespace SME.SGP.Aplicacao.Queries.ConselhoClasse.ObterTotalAlunosSemFrequenciaPorTurmaQuery
Esse também, só até aplicação

2022-04-26 12:05 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterTotalAulasPorAlunoTurmaQuery/ObterTotalAulasPorAlunoTurmaQuery.cs
> +namespace SME.SGP.Aplicacao.Queries.ConselhoClasse.ObterTotalAulasPorAlunoTurmaQuery
Esse também, só até aplicação

2022-04-26 12:05 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterTotalAulasPorAlunoTurmaQuery/ObterTotalAulasPorAlunoTurmaQueryHandler.cs
> +namespace SME.SGP.Aplicacao.Queries.ConselhoClasse.ObterTotalAulasPorAlunoTurmaQuery
Esse também, só até aplicação

2022-04-26 12:05 UTC, viniciusnyari commented on teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/RetornarTotalAulasNaoRealizamFrequenciaTeste.cs
> +namespace SME.SGP.TesteIntegracao.ConselhoDeClasse
Ajuste o namespace

2022-04-26 12:05 UTC, viniciusnyari commented on teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/RetornarTotalAulasRealizamFrequenciaTeste.cs
> +namespace SME.SGP.TesteIntegracao.ConselhoDeClasse
Ajustar namespace

2022-04-26 12:39 UTC, merged