feature/61261 - criação endpoint para obter total aulas que não lançam nota
prefeiturasp/SME-NovoSGP pull request #9257
Opened 2022-04-21 17:10 UTC by danilosoad

AB#61261

2022-04-21 20:38 UTC, rafalosiamcom requested changes
Criar testes de Integração para garantir o funcionamento do endpoint

2022-04-21 20:38 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
> +                        join componente_curricular cc on cc.id = fa.disciplina_id::int8
remover descrição e join

2022-04-21 20:38 UTC, rafalosiamcom commented on teste/SME.SGP.Aplicacao.Teste/CasosDeUso/ObterTotalAulasNAoLancamNotaUseCaseTeste.cs
> +            Assert.NotNull(totalAulas);
mesmo caso do outro PR, só esta testando o valor mockado

2022-04-26 14:48 UTC, viniciusnyari requested changes

2022-04-26 14:48 UTC, viniciusnyari commented on src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
> +                        and fa.tipo  = 1
coloca esse tipo como parâmetro lá embaixo para saber do que se trata esse tipo = 1

2022-04-26 15:01 UTC, viniciusnyari approved these changes

2022-04-26 15:01 UTC, merged