fix/63464 - ajuste para editar as frases de recomendação do aluno
prefeiturasp/SME-NovoSGP pull request #9339
Opened 2022-04-28 19:32 UTC by murilobarr0s

AB#63464

2022-04-28 21:03 UTC, rafalosiamcom requested changes

2022-04-28 21:03 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/ConselhoClasseAlunoRecomendacao/SalvarConselhoClasseAlunoRecomendacao/SalvarConselhoClasseAlunoRecomendacaoCommandHandler.cs
> +                await repositorioConselhoClasseAlunoRecomendacao.ExcluirRecomendacoesPorConselhoAlunoId(request.ConselhoClasseAlunoId);
essa estratégia de excluir e depois incluir denovo ta gerando problemas em produção em vários assuntos com locks.
Temos que bolar outra solução

2022-05-03 13:38 UTC, viniciusnyari requested changes

2022-05-03 13:38 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Commands/ConselhoClasseAlunoRecomendacao/SalvarConselhoClasseAlunoRecomendacao/SalvarConselhoClasseAlunoRecomendacaoCommandHandler.cs
> +            foreach(var recomendacaoId in recomendacoesAlunoFamilia)
Evitar esse foreach com uma inserção em massa e deixar o foreach lá de cima só para tratar o que é inserção e o que é remoção.

2022-05-03 14:03 UTC, viniciusnyari approved these changes

2022-05-09 12:57 UTC, rafalosiamcom requested changes

2022-05-09 12:57 UTC, rafalosiamcom commented on teste/SME.SGP.TesteIntegracao/Ao_obter_recomendacoes.cs
> -        public async Task Deve_inserir_recomendacao_aluno()
Não excluir o teste criado, apenas remova o [Fact]

2022-05-09 12:59 UTC, murilobarr0s commented on teste/SME.SGP.TesteIntegracao/Ao_obter_recomendacoes.cs
> -        public async Task Deve_inserir_recomendacao_aluno()
feito

2022-05-09 13:02 UTC, rafalosiamcom approved these changes

2022-05-09 13:02 UTC, merged