Story_62257 -> Release
prefeiturasp/SME-NovoSGP pull request #9394
Opened 2022-05-04 18:56 UTC by FernandoGroeler

AB#62257

2022-05-04 19:40 UTC, rafalosiamcom requested changes

2022-05-04 19:40 UTC, rafalosiamcom commented on scripts/V541__NOVA_TABELA_FREQUENCIA_TURMA_EVASAO.sql
> +CREATE INDEX frequencia_turma_evasao_turma_id_idx ON public.frequencia_turma_evasao USING btree (turma_id);
Criar indice também em Mes pois será sempre pesquisado com o mês para verificar a existência

2022-05-04 19:40 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/FrequenciaTurmaEvasao/LimparFrequenciaTurmaEvasaoPorTurmasEMeses/LimparFrequenciaTurmaEvasaoPorTurmasEMesesCommand.cs
> +    public class LimparFrequenciaTurmaEvasaoPorTurmasEMesesCommand : IRequest<bool>
Falta a classe de Validator

2022-05-04 19:40 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Commands/FrequenciaTurmaEvasao/RegistrarFrequenciaTurmaEvasao/RegistrarFrequenciaTurmaEvasaoCommand.cs
> +    public class RegistrarFrequenciaTurmaEvasaoCommand : IRequest<long>
Falta a classe de Validator

2022-05-04 20:07 UTC, FernandoGroeler commented on scripts/V541__NOVA_TABELA_FREQUENCIA_TURMA_EVASAO.sql
> +CREATE INDEX frequencia_turma_evasao_turma_id_idx ON public.frequencia_turma_evasao USING btree (turma_id);
Índice criado.

2022-05-04 20:08 UTC, FernandoGroeler commented on src/SME.SGP.Aplicacao/Commands/FrequenciaTurmaEvasao/LimparFrequenciaTurmaEvasaoPorTurmasEMeses/LimparFrequenciaTurmaEvasaoPorTurmasEMesesCommand.cs
> +    public class LimparFrequenciaTurmaEvasaoPorTurmasEMesesCommand : IRequest<bool>
Classe adicionada.

2022-05-04 20:08 UTC, FernandoGroeler commented on src/SME.SGP.Aplicacao/Commands/FrequenciaTurmaEvasao/RegistrarFrequenciaTurmaEvasao/RegistrarFrequenciaTurmaEvasaoCommand.cs
> +    public class RegistrarFrequenciaTurmaEvasaoCommand : IRequest<long>
Classe adicionada.

2022-05-05 10:36 UTC, rafalosiamcom approved these changes

2022-05-05 10:36 UTC, merged