Fix/63549 - Dados estão incorretos na tela
prefeiturasp/SME-NovoSGP pull request #9397
Opened 2022-05-04 19:49 UTC by danilosoad

AB#63549

2022-05-04 21:14 UTC, viniciusnyari approved these changes

2022-05-05 10:34 UTC, rafalosiamcom requested changes
Faltaram testes de integração na nova consulta e também considerar a possibilidade de o componente não lançar frequencia.

2022-05-05 10:34 UTC, rafalosiamcom commented on src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs
> +            var sql = @"select disciplina_id as disciplinaid, SUM(total_aulas) as TotalAulas from frequencia_aluno fa
Se o componente consultado não fizer registro de frequência então não teremos nada nessa entidade frequencia_aluno.
O mesmo ocorre se o professor não lançar a frequência.

2022-05-05 17:16 UTC, danilosoad commented on src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs
> +            var sql = @"select disciplina_id as disciplinaid, SUM(total_aulas) as TotalAulas from frequencia_aluno fa
ajustado

2022-05-05 17:34 UTC, rafalosiamcom requested changes

2022-05-05 17:34 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
> +            var teste = Enumerable.Empty<TotalAulasPorAlunoTurmaDto>();
alterar o nome da variavel para algo mais sugestivo

2022-05-05 20:00 UTC, merged