Story/64613 to release
prefeiturasp/SME-NovoSGP pull request #9868
Opened 2022-06-24 21:03 UTC by FernandoGroeler

AB#64613

2022-06-24 21:09 UTC, viniciusnyari approved these changes

2022-06-27 12:26 UTC, rafalosiamcom requested changes

2022-06-27 12:26 UTC, rafalosiamcom commented on src/SME.SGP.Api/Controllers/EncaminhamentoAEEController.cs
> +        [Route("obterpaai")]
remover o obter da Rota.. o método já é GET

2022-06-27 12:26 UTC, rafalosiamcom commented on src/SME.SGP.Aplicacao/Queries/Responsaveis/ObterResponsavelAtribuidoUePorUeTipo/ObterResponsavelAtribuidoUePorUeTipoQueryValidator.cs
> +                .WithMessage("O código da Ue deve ser informado.");
Deixar as validações mais específicas para facilitar a identificação no caso de erro. ex: O código da Ue deve ser informado para obter responsáveis atribuídos a escola

2022-06-27 12:46 UTC, FernandoGroeler commented on src/SME.SGP.Api/Controllers/EncaminhamentoAEEController.cs
> +        [Route("obterpaai")]
Ajustado.

2022-06-27 12:48 UTC, rafalosiamcom approved these changes

2022-06-27 12:48 UTC, merged