Ajuste
prefeiturasp/SME-NovoSGP pull request #9899
Opened 2022-06-28 17:31 UTC by MaxAMcom

[AB#67401](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67401)

2022-06-28 19:53 UTC, rafalosiamcom requested changes

2022-06-28 19:53 UTC, rafalosiamcom commented on src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
> +                var alunosTurma = await mediator.Send(new ObterAlunosEolPorCodigosQuery(codigoAlunos));
não da pra fazer a consulta no EOL fora do foreach de notas em aprovação ?
assim consulta uma vez só

2022-06-29 14:49 UTC, MaxAMcom commented on src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
> +                var alunosTurma = await mediator.Send(new ObterAlunosEolPorCodigosQuery(codigoAlunos));
Ajustado

2022-06-29 14:52 UTC, FernandoGroeler approved these changes

2022-06-29 17:15 UTC, rafalosiamcom approved these changes

2022-06-29 17:15 UTC, merged