UE já atribuída, aparecendo na lista de UEs sem atribuição
prefeiturasp/SME-NovoSGP pull request #9905
Opened 2022-06-28 20:22 UTC by thiiagofernando

AB#68091
AB#68092

2022-06-28 20:31 UTC, viniciusnyari requested changes

2022-06-28 20:31 UTC, viniciusnyari commented on src/SME.SGP.Aplicacao/Consultas/ConsultaDres.cs
> +            catch (Exception ex)
Remove o tratamento

2022-06-28 20:34 UTC, viniciusnyari approved these changes

2022-06-28 20:43 UTC, viniciusnyari approved these changes

2022-06-28 22:07 UTC, thiiagofernando commented on src/SME.SGP.Aplicacao/Consultas/ConsultaDres.cs
> +                for (int i = 0; i < uesParaAtribuicao.Count; i++)
alterado para foreach

2022-06-29 17:11 UTC, rafalosiamcom approved these changes

2022-06-29 17:12 UTC, merged