Release - Story/66608
prefeiturasp/SME-NovoSGP pull request #9941
Opened 2022-07-01 12:52 UTC by viniciusnyari

Release - Story/66608

2022-07-01 12:55 UTC, DanylloAntunes approved these changes

2022-07-01 15:03 UTC, rafalosiamcom requested changes

2022-07-01 15:03 UTC, rafalosiamcom commented on teste/SME.SGP.TesteIntegracao/Aula/Ao_alterar_aula_unica.cs
> +            excecao.Message.ShouldBe("Já existe uma aula criada neste dia para este componente curricular");
Mensagens de exceção mudam com frequência e assim vai quebrar o teste.

2022-07-01 15:03 UTC, rafalosiamcom commented on teste/SME.SGP.TesteIntegracao/Ao_registrar_anotacao_fechamento.cs
> +namespace SME.SGP.TesteIntegracao.TestarAnotacaoFechamentoAluno
porque o "Testar"AnotacaoFechamentoAluno no pacote ? se o pacote já é de TesteIntegracao o Testar é redundante

2022-07-01 16:21 UTC, viniciusnyari commented on teste/SME.SGP.TesteIntegracao/Ao_registrar_anotacao_fechamento.cs
> +namespace SME.SGP.TesteIntegracao.TestarAnotacaoFechamentoAluno
Ajustado. Removi de todos.

2022-07-01 16:22 UTC, viniciusnyari commented on teste/SME.SGP.TesteIntegracao/Aula/Ao_alterar_aula_unica.cs
> +            excecao.Message.ShouldBe("Já existe uma aula criada neste dia para este componente curricular");
Removido.

2022-07-04 12:36 UTC, rafalosiamcom approved these changes

2022-07-04 12:36 UTC, merged