Story/62650 --> Release
prefeiturasp/SME-NovoSGP pull request #9978
Opened 2022-07-07 19:57 UTC by viniciusnyari

2022-07-07 19:58 UTC, danilosoad approved these changes

2022-07-08 12:16 UTC, rafalosiamcom requested changes

2022-07-08 12:16 UTC, rafalosiamcom commented on teste/SME.SGP.TesteIntegracao/Frequencia/Ao_realizar_lancamento_de_justificativa.cs
> +            async Task doExecutar() { await SalvarAnotacaoFrequenciaAlunoUseCase(parametrosFrontEnd); }
não entendi porque esta gerando essa Task pra chamar no ThrowAsync ao invés de usar o próprio UseCase

2022-07-08 12:31 UTC, viniciusnyari commented on teste/SME.SGP.TesteIntegracao/Frequencia/Ao_realizar_lancamento_de_justificativa.cs
> +            async Task doExecutar() { await SalvarAnotacaoFrequenciaAlunoUseCase(parametrosFrontEnd); }
Estamos seguindo a implementação da documentação do shouldly
https://docs.shouldly.io/documentation/exceptions/throw

2022-07-08 12:46 UTC, rafalosiamcom commented on teste/SME.SGP.TesteIntegracao/Frequencia/Ao_realizar_lancamento_de_justificativa.cs
> +            async Task doExecutar() { await SalvarAnotacaoFrequenciaAlunoUseCase(parametrosFrontEnd); }
a documentação mostra uma Task sendo usada na função.. vc já tem essa Task, é a SalvarAnotacaoFrequenciaAlunoUseCase, é só chamar ela da mesma forma

2022-07-08 13:37 UTC, viniciusnyari commented on teste/SME.SGP.TesteIntegracao/Frequencia/Ao_realizar_lancamento_de_justificativa.cs
> +            async Task doExecutar() { await SalvarAnotacaoFrequenciaAlunoUseCase(parametrosFrontEnd); }
Ajustado.

2022-07-08 14:57 UTC, rafalosiamcom approved these changes

2022-07-08 14:57 UTC, merged